### ISSUE TITLE
A7-TotLM-BG2EE.ini downloaded today has different file size. Many others too, verified on git version, check remote version by browser too

### ISSUE THREAD

**Issue by davideOXC** [EE-Mod-Setup/EE-Mod-Setup#10]
![image](https://user-images.githubusercontent.com/7692937/63643584-a9c26800-c6d3-11e9-888e-474a7b7024ca.png)

![image](https://user-images.githubusercontent.com/7692937/63643605-3b31da00-c6d4-11e9-8fe1-6d6071710a1d.png)

**Comment by davideOXC** [comment]
There are many differences ... but today I downloaded an extended version of your compilation EET_Roxannes_Campaign2019.ini with the tool downloaded from git as zip and I got only the errors notice into issue #8. Now I have cloned the repository by git client and I compared by WinMerge the two folder: he are a lot of difference, some on mod that I downloaded with success.

![image](https://user-images.githubusercontent.com/7692937/63643668-f5761100-c6d5-11e9-87df-a823ad7236a4.png)

May I help you to fix the repository or do you prefer check it by your self ?

**Comment by davideOXC** [comment]
WinMerge report by compare tool folder git zip downloaded and git clone
[diff.csv.txt](https://github.com/EE-Mod-Setup/EE-Mod-Setup/files/3537653/diff.csv.txt)

**Comment by RoxanneSHS** [comment]
This local compare and update is not something to be fed back into the tool's database. It is only used to compare the already downloaded version that may be found in your download directory with the data found on the network to determine whether to download a mod again or use the already locally existing version.
So, all of these are only relevant locally and no need to be kept synchronized outside of your local machine,
