### ISSUE TITLE
Chinese translation for a number of mods...

### ISSUE THREAD

**Issue by wuxiangjinxing** [EE-Mod-Setup/EE-Mod-Setup#100]
Hi,

I made Chinese translation for some of the mods available in the EE-Mod-Setup tool.  Could you maybe incorporate them?

The mods I finished Chinese translations are: (all updated to the latest version in the setup tool)
atweaks
bg1 NPC project
Afaaq, Djinni Companion
Drizzt Saga (There is a duplicated language file in the big project fix folder/drizztsaga/_copy, just FYI)
DSotSC
item upgrade
Longer Road
Ntotsc
Solaufein
Stratagems
TDD + TDDz
The Grey Clan 1e
Thalan item upgrade
BG2 Ub

I made these Chinese translation by simply translate all the strings in english tra files.  That's why you will see most of the new tras are still either in 'english' or 'american' folders, though the contents are Chinese now.  The BG2-ub mod is also given new translation files because the Chinese translation available with the setup tool is VERY unfinished.  

All the translation files are encoded in utf-8 now.  Sorry I don't well understand how Weidu works, but as I know they shall not go though another round of 'HANDLE_CHARSETS' process or else everything becomes garbled.  It will be neccessary to change the tp2 or tpa files to remove the corresponding commands.

The new translations are in the attachment.
[New Chinese Translations.zip](https://github.com/EE-Mod-Setup/EE-Mod-Setup/files/13331134/New.Chinese.Translations.zip)

Thanks a lot for making such an awesome tool and the Sandrah saga mod 💯

**Comment by RoxanneSHS** [comment]
Great work.
However consider the following:
1) Install Tool only manages mod installations but does not maintain the mods itself. There are a number of mods (e.g. Drizzt Saga or TDDZ and Longer Road or Solaufein that I maintain as well and for those I will add your tranlations
2) In your zip file, the subfolders are English or American but should be named Chinese.
3) I will add to Chinese option in Install Tool for all the mods that I can handle myself, others may follow when the respective modder has made an update. I will let you know which ones I have done or you can monitor the updates yourself on Github.

**Comment by wuxiangjinxing** [comment]
Thanks!  I left the subfolders as english or american mostly because I don't want to modify tp2 files.  Please feel free to rename the subfolders (and make any neccessary adjustments).  Actually I expect to learn from you on how to avoid the 'double handle_charsets makes utf-8 garbled' issue in a clean way.  Tbh, when I was installing these mods myself, this is a huge trouble :(

**Comment by RoxanneSHS** [comment]
There is some way to exclude files from excluding files from handle charsets but it is cumbersome and I forgot how to do it...Since I only deal with EE games nowadays and all my mods are only for EE I do no longer need to worry and can have all in utf-8 right away without the need to change files. So it is only relevant for mods that still think they need to serve old game (which is not my problem, so I need not to care).

**Comment by wuxiangjinxing** [comment]
Maybe I was misunderstanding what's the problem, but if I just replaced the tra files in english/american subfolders with utf-8 encoded Chinese translation and install the mods, for some mods (i.e. BG1 npc project), a number of tra files starting with fl# will be automatically generated (i.e. fl#Setup.tra), and all my translated tra files will become garbled (and certainly the installation process is ruined).  I need to go into the tp2 (or tpa) files and remove the handle_charsets commands to avoid this issue.

**Comment by RoxanneSHS** [comment]
For your local installation that would work - put your translated files into english folder of the mod and remove the handle charset from tp2. The problem may be to select the right dialog.tlk file of the game because you may want to have your text most likely in the Chinese version of the game. Install Tool would detect automatically that your game language is Chinese, mods may have a selection when the setup opens. Or look for WeiDu.conf in the game folder and see that it points to the right language (it is a text file that any editor can open).

**Comment by wuxiangjinxing** [comment]
I think the problem is due to weidu version.

According to [](https://www.gibberlings3.net/forums/topic/32369-tutorial-how-to-properly-handle-mod-translation-by-using-handle_charsets-function-with-auto_tra/), there are two different behaviors:

 **How it was handled before:**

    translators provide .tra files using their own preferred local encoding
    HANDLE_CHARSETS function convert those files into UTF8 encoding when mod was installed on enhanced game editions

**How it is handled now:**

    translators provide .tra files using UTF8 encoding
    when the mod is installed on classic game editions, the temporary copy of translation files are converted into ASCII encoding so the source files are not touched
    no modification of original UTF8-files when mod is installed on enhanced game editions

Thus, the best way to do the translation should be:
1) Use weidu.exe v249 (latest version on github ) [https://github.com/WeiDUorg/weidu](url).  FYI the weidu provided by the setup tool is v247
2) Convert all the localization tras to utf-8 BEFORE the installation.

I checked mods provided with a CH translation option in the setup tool.  Most of the tras are still encoded using GB2312, but there are also some encoded with utf-8 already (i.e. Tweaks-Anthology).  I would suggest making it consistent, and convert the tras to utf-8 using some batch scripts instead of the weidu handle_charsets function.

**Comment by RoxanneSHS** [comment]
In this case, the problem is with new weidu...how will you make long retired modders change their files to utf-8?

**Comment by wuxiangjinxing** [comment]
We can write a python script to convert all tras to utf-8 after the extraction and before the translation, or there are numerous other methods to do it.  There is no need to contact retired modders.

**Comment by RoxanneSHS** [comment]
That sounds fine...only that I am no programmer and such a feature is beyond my skills...

**Comment by RoxanneSHS** [comment]
Also - is it not necessary to remove any charset conversion from every tp2 file of the mods? (or does new weidu do that?)

**Comment by RoxanneSHS** [comment]
Understood for new weidu version.

I made a trial with your script. I put a Polish ANSI tra file and run the bat. I get a UTF-8 file but only with half of the first line in tra. The rest is eliminated. Same if I run it on multiple files at once.

**Comment by wuxiangjinxing** [comment]
Oh, if you want to use the batch on other languages, you need to modify the batch (GBKtoUTF8.bat) with the correct source encoding, this batch is strictly used to convert GBK to utf-8.

The core command in this batch is: iconv -f GBK -t UTF-8 %%i > %%i.bkp.  

If it is a Polish ANSI, you can change GBK to windows-1252, so iconv -f windows-1252 -t UTF-8 %%i > %%i.bkp.

**Comment by RoxanneSHS** [comment]
Great - would 1252 also work for Russian or is that something else again (I checked that it seems to work for Spanish as well)?

**Comment by wuxiangjinxing** [comment]
Russian is mostly windows-1251

But there is a more severe problem.  This iconv tool requires the user to know the exact encoding of the source files.  If the encoding is wrong (i.e. we do iconv on a file that is already in utf-8), then we get garbled texts again.

We might be able to use something like python chardet library to guess the encoding of input files but obviously that's not stable.  I guess the best way is to tell the user to keep an eye on their tra files if they are using a translation.

**Comment by RoxanneSHS** [comment]
Yes it was 1251 for my current case.

I will spend some time to look at the mods I have under maintenance and fix them with the knowledge now gained. Next I will look at some other translations from your package and see if anything can be done on an individual basis, maybe by putting new files into fixpack. Then see what is still left unresolved....there seems to be no quick and easy solution that fits all.

**Comment by wuxiangjinxing** [comment]
Sorry I made some mistakes in the previous file.  Some strings are missing, causing problems during installation.

Fixed in the new one.  Also I included a more complete translation of the Ascenscion mod, and the translation for Sarelieth and Amber.

[ChineseMods.zip](https://github.com/EE-Mod-Setup/EE-Mod-Setup/files/13345566/ChineseMods.zip)

**Comment by RoxanneSHS** [comment]
Do you remember which mods have mistakes? I only used DrizztSaga and Longer Road so far, there was also an update for Solaufein recently.

**Comment by wuxiangjinxing** [comment]
SCS 从 Windows 版邮件发送 发件人: Roxanne发送时间: Tuesday, November 14, 2023 2:16 AM收件人: EE-Mod-Setup/EE-Mod-Setup抄送: wuxiangjinxing; Author主题: Re: [EE-Mod-Setup/EE-Mod-Setup] Chinese translation for a number of mods... (Issue #100) Do you remember which mods have mistakes? I only used DrizztSaga and Longer Road so far, there was also an update for Solaufein recently.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by wuxiangjinxing** [comment]
BG1 NPC project and SCS

**Comment by RoxanneSHS** [comment]
Status
I have updated mods and install tool for new Chinese translations for all mods that I can control. You can check in the recent github updates.
Of the remaining ones, only Ascension mod already has a Chinese option. For all others, the respective modders would need to include the translations and modify the tp2-files. (Install tool could replace the old Ascension tra-files with the new ones but it would be better to update the mod instead).
There is an option to use fixpack for those other mods but that would only work as long as the mods are not updated - I would not want to use that option (that was done in the past at times but always led to things becoming obsolete quickly...so no longer something I like to do).
