### ISSUE TITLE
Could you add these mods to BG2 launcher?

### ISSUE THREAD

**Issue by Pirate300** [EE-Mod-Setup/EE-Mod-Setup#103]
1- https://downloads.weaselmods.net/download/the-bloodied-stings-of-barovia/

2- https://downloads.weaselmods.net/download/juniper-and-the-stone-leech/

3- https://downloads.weaselmods.net/download/in-love-undeath/

**Comment by RoxanneSHS** [comment]
Probably when they are consolidated and tested, i.e. a bit later
