### ISSUE TITLE
Trouble installing following mods:

### ISSUE THREAD

**Issue by Pirate300** [EE-Mod-Setup/EE-Mod-Setup#104]
The following mod(s) could not be downloaded:

   Alabaster Sands: The Mod itself (unspecified)
          https://www.dropbox.com/scl/fi/3lvllhnfllyjuoiap305q/AlabasterSands-v1.4.zip?rlkey=p0rv6b1s1vboq5xz8pxy5awvv&dl=1
   I Shall Never Forget: The Mod itself (unspecified)
          https://www.dropbox.com/scl/fi/oq7o252b1lqj8ubvqtbka/I-Shall-Never-Forget-v6.1.zip?rlkey=ruuh6zl3h0usholpkli98uv0n&dl=1
   Innershade: The Mod itself (unspecified)
          https://www.dropbox.com/scl/fi/929afny8za307kz08tae2/Innershade-v11.1.zip?rlkey=9tf7lf0c2lhgm149ek96p0xko&dl=1
   Tales of the Deep Gardens: The Mod itself (unspecified)
          https://www.dropbox.com/scl/fi/uxag4gicdj1ywwvjk8imb/Tales-of-the-Deep-Gardens-v12.9.zip?rlkey=ct8z2bc856s13jpfmspxq6bry&dl=1
   The White Queen: The Mod itself (unspecified)
          https://www.dropbox.com/scl/fi/01r6q35djvm5k23riv57u/The-White-Queen-v6.93.zip?rlkey=0u99pqcr7ckho9risclugcisc&dl=1
   Oozes Lounge: The Mod itself (unspecified)
          https://www.dropbox.com/scl/fi/5oid4oym5w0yoaa32rxjf/Oozes-Lounge-v2.93.zip?rlkey=afzpasej0yrw3ibeba5znxyh0&dl=1
   Southern Edge: The Mod itself (unspecified)
          https://www.dropbox.com/scl/fi/7r4xwjgv4mltgxqft5cnb/SouthernEdge-v4.2.zip?rlkey=jws73mrpdao0y81n571572bfn&dl=1

error seems to occur because "unspecified" names. Tried to fix it by changing filenames at Mod.ini, but it won't work!

**Comment by RoxanneSHS** [comment]
Just checked and all links worked well. Either this was a temporary issue or some local restriction you have.
