### ISSUE TITLE
How can I identify what causes these errors?

### ISSUE THREAD

**Issue by Pirate300** [EE-Mod-Setup/EE-Mod-Setup#105]
Stopping installation because of error.

ERROR Installing [Include arcane spells from Icewind Dale: Enhanced Edition], rolling back to previous state
Will uninstall 299 files for [STRATAGEMS/SETUP-STRATAGEMS.TP2] component 1500.
Uninstalled    299 files for [STRATAGEMS/SETUP-STRATAGEMS.TP2] component 1500.
ERROR: Failure("resource [SPWI525A.bam] not found for 'COPY'")
Please make a backup of the file: SETUP-STRATAGEMS.DEBUG and look for support at: For help troubleshooting installation problems, go to the Sword Coast Stratagems forum at forums.gibberlings3.net.
Automatically Skipping [Include arcane spells from Icewind Dale: Enhanced Edition] because of error.
Using Language [English]
weidu_external/lang/english/ubsetup.tra file not found. Skipping...
[.\lang\en_us\dialog.tlk] created, 236619 string entries

NOT INSTALLED DUE TO ERRORS Include arcane spells from Icewind Dale: Enhanced Edition

E:\SteamLibrary\steamapps\common\Baldur's Gate II Enhanced Edition>
ERROR: Failure("resource [SPWI525A.bam] not found for 'COPY'")
Include arcane spells from Icewind Dale (Sword Coast Stratagems) was not installed due to errors.

You can try to repair the problem and start the installation of the component again. In this case please select "retry" after the repair.

If you don't want to spent time for that now, you can also continue without the component or exit the program. The Setup will continue with the installation of that component.
Enter [r]etry, [c]ontinue or [e]xit.

ERROR Installing [Initialise AI components (required for all tactical and AI components)], rolling back to previous state
Will uninstall 940 files for [STRATAGEMS/SETUP-STRATAGEMS.TP2] component 5900.
Uninstalled    940 files for [STRATAGEMS/SETUP-STRATAGEMS.TP2] component 5900.
ERROR: Not_found
Please make a backup of the file: SETUP-STRATAGEMS.DEBUG and look for support at: For help troubleshooting installation problems, go to the Sword Coast Stratagems forum at forums.gibberlings3.net.
Automatically Skipping [Initialise AI components (required for all tactical and AI components)] because of error.
Using Language [English]

SKIPPING: [Smarter general AI]
	This component requires the core "initialise AI" component to be installed

SKIPPING: [Better calls for help]
	This component requires the core "initialise AI" component to be installed

SKIPPING: [Smarter Mages]
	This component requires the core "initialise AI" component to be installed

SKIPPING: [Smarter Priests]
	This component requires the core "initialise AI" component to be installed

SKIPPING: [Potions for NPCs]
	This component requires the core "initialise AI" component to be installed

SKIPPING: [Improved Spiders]
	This component requires the core "initialise AI" component to be installed

SKIPPING: [Improved golems]
	This component requires the core "initialise AI" component to be installed

SKIPPING: [Improved fiends and celestials]
	This component requires the core "initialise AI" component to be installed

SKIPPING: [Smarter genies]
	This component requires the core "initialise AI" component to be installed

SKIPPING: [Smarter dragons]
	This component requires the core "initialise AI" component to be installed

SKIPPING: [Smarter beholders]
	This component requires the core "initialise AI" component to be installed

SKIPPING: [Smarter mind flayers]
	This component requires the core "initialise AI" component to be installed

SKIPPING: [Smarter githyanki]
	This component requires the core "initialise AI" component to be installed

SKIPPING: [Improved Vampires]
	This component requires the core "initialise AI" component to be installed

SKIPPING: [Smarter Throne of Bhaal final villain]
	This component requires the core "initialise AI" component to be installed

SKIPPING: [Smarter Illasera]
	This component requires the core "initialise AI" component to be installed

SKIPPING: [Smarter Gromnir]
	This component requires the core "initialise AI" component to be installed

SKIPPING: [Smarter Yaga-Shura]
	This component requires the core "initialise AI" component to be installed

SKIPPING: [Smarter Abazigal]
	This component requires the core "initialise AI" component to be installed

SKIPPING: [Ascension versions of Irenicus and Sendai use SCS abilities and AI]
	This component requires the core "initialise AI" component to be installed

SKIPPING: [Ascension demons use SCS abilities and AI]
	This component requires the core "initialise AI" component to be installed
weidu_external/lang/english/ubsetup.tra file not found. Skipping...

NOT INSTALLED DUE TO ERRORS Initialise AI components (required for all tactical and AI components)

E:\SteamLibrary\steamapps\common\Baldur's Gate II Enhanced Edition>
ERROR: cannot convert SFO_reserved_array_WIZ_death_41 or %SFO_reserved_array_WIZ_death_41% to an integer
ERROR: Not_found
Initialise AI components (required for all tactical and AI components) (Sword Coast Stratagems) was not installed due to errors.

You can try to repair the problem and start the installation of the component again. In this case please select "retry" after the repair.

If you don't want to spent time for that now, you can also continue without the component or exit the program. The Setup will continue with the installation of that component.
Enter [r]etry, [c]ontinue or [e]xit.

**Comment by RoxanneSHS** [comment]
You are installing mods on SteamLibrary\steamapps\ which is a protected directory and so you will have loads of download and write errors.
Check the pdf file coming with the install tool about how to use game copies in an unprotected part of your PC but never original games.
