### ISSUE TITLE
Issue mentioned previously: Mods download but don't match file name.

### ISSUE THREAD

**Issue by Pirate300** [EE-Mod-Setup/EE-Mod-Setup#106]
![2023-12-05 (13)](https://github.com/EE-Mod-Setup/EE-Mod-Setup/assets/54774500/fa7ce5dc-3f29-4086-b74b-9873860b7ee8)

Sorry for bringing this again, but this is the problem! I have found that the filename is not the same for these mods.
Instead of, for example, "The White Queen v6.93.zip" mod manager looks for  "unspecified".

**Comment by RoxanneSHS** [comment]
This is what the original file in the mod manager says
Save=The White Queen v6.93.zip in whitequeen.ini App/config/global.  
If you see something else, it must have been erroneously changed by some local error. This may have happened if you used the tool before and had some error connecting to the network or something like that.

**Comment by Pirate300** [comment]
Roxanne, I looked after in App/config/global and it seems to work now!
Before triying this, I was changing the names from \App\Config\BG2EE\Mod.ini
Thank you! Seems to be working now :)
