### ISSUE TITLE
Any chance to update following mods for BG2 to their latest version?

### ISSUE THREAD

**Issue by Ahriman40** [EE-Mod-Setup/EE-Mod-Setup#108]
**Quest Mods:**
Ascension
Dungeon Crawl
Heroes, Thieves and Moneylenders
The Sellswords

**Mini-Mods:**
Lucy the Wyvern
Southern Edge

**Tactical Encounters:**
P&P Celestials

**Rules and Tweaks:**
Almateria's Restoration Project
Enhanced Powergaming Scripts
Improved Shamanic Dance
Scales of Balance
SubtleD's Spell Tweaks

**Stores and Items:**
Made in Heaven - Item Pack
SKIE: THE COST OF ONE GIRL’S SOUL
Siege of Dragonspear to Baldur's Gate II: Enhanced Edition Item Upgrade

**Charakter Kits:**
The Artisan's Kitpack
Bardic Wonders
Sorcerer's Place Collection
Spirit Hunter
Warlock

**Graphic, Portraits and Sound Mods:**
DragonspearUI

Also a question - in some mods in the catalogue it says '(GitHub latest Release)' - does it actually work and always download latest version? I tried it with 'NPCs Enhanced for Everyone' but it didn't download latest release.

Also any chance to add Item and Spell Revision Revised as an option to install?

**Comment by RoxanneSHS** [comment]
Did you look at those so-called latest versions, what they do and who contributed them.
I would rather go to well tested and stable ones made by experts than to chase bugs for others.
No, thank you.

**Comment by Ahriman40** [comment]
_Did you look at those so-called latest versions, what they do and who contributed them._
Bug fixes and they are contributed by authors of said mods from what i see.

_I would rather go to well tested and stable ones made **by experts** than to chase bugs for others._
I not sure i understand, why would you be bug-tester for latest release of mods if a user chooses to install it? Also who is considered 'an expert'? Any mod author?
