### ISSUE TITLE
Fishing for Trouble - confirmed different file name when downloaded (issue #8)

### ISSUE THREAD

**Issue by davideOXC** [EE-Mod-Setup/EE-Mod-Setup#11]
Name=Fishing for Trouble
Rev=3.2.4
Type=S,T,E
Link=http://www.spellholdstudios.net/ie/fft
Down=http://lynxlynx.info/ie/modhub.php?InfinityMods/FishingForTrouble&pre
Save=InfinityMods-FishingForTrouble-3.2.4-0-g363afdd.zip --> **InfinityMods-FishingForTrouble-3.2.4-0-gf4cd8db.zip**
Size=117127786 --> 177112442

**Comment by davideOXC** [comment]
https://github.com/EE-Mod-Setup/EE-Mod-Setup/blob/master/App/Config/Global/fishingfortrouble.ini

**Comment by RoxanneSHS** [comment]
updated
