### ISSUE TITLE
EET module translation error hard locking instalation

### ISSUE THREAD

**Issue by noderministicsingularity** [EE-Mod-Setup/EE-Mod-Setup#110]
installing eet (the mod) with the tool trow back a missing translation file error for a line in the english translation. i am not shure i understood that corectly. altough the tool literaly ask me to 'repair the issue' and 'email the debug file to k4thos'  i'm prety shure you are the one actively working on the eetsetup tool. so i'm just gonna try to post this here as i'm not shure if k4thos is still actively working on this. in 2023
![Sandfgjs titre](https://github.com/EE-Mod-Setup/EE-Mod-Setup/assets/96703438/3e18ff1c-4126-401e-88d6-a5ae857aae00)
[SETUP-EET.DEBUG.txt](https://github.com/EE-Mod-Setup/EE-Mod-Setup/files/13695038/SETUP-EET.DEBUG.txt)

i changed the .debug sufix to a .txt sufix to be able to upload it. 
if that is corrupt code in the localisation of the eet master files there is no way i can proceed to an instalation. much less 'repair the issue' even tough i would really like to. 

any advices ? what can i do next.

also, totaly unrelated, but do you remember the semi unfixable issue with files being renamed as 'master.zip' ?  now dropbox links can do the same and put '   'undefined'   '  as file names in the mod.ini files    same style of bug.  can be work around same way as i descriped with master.zip. manualy that is.

**Comment by RoxanneSHS** [comment]
You install on steam/steamapps instead on using unprotected copies of the game for modding. This always leads to read/write errors. Check the pdf-manual that is in the tool download package to see details.

**Comment by noderministicsingularity** [comment]
i love this shit. can you take my screenshot and get them framed and hang them in your livingroom please ? 
![Ssdfghans titre](https://github.com/EE-Mod-Setup/EE-Mod-Setup/assets/96703438/72fb01a6-182a-46bc-ae73-637ac251a698)
![Sansdfgndgfh titre](https://github.com/EE-Mod-Setup/EE-Mod-Setup/assets/96703438/aa845b45-faa7-4d0e-913e-766bfe7eae88)
![Sans fgjnhfgdtitre](https://github.com/EE-Mod-Setup/EE-Mod-Setup/assets/96703438/eb75d57d-e4a9-49cd-a0db-d73bbe79d9dc)

**Comment by noderministicsingularity** [comment]
beside the software is saying that the line with no translation is in the eet core files. not in the base game files.

**Comment by RoxanneSHS** [comment]
EET processes try to run in the steam directory where your game is. If that is protected, then things may fail.
Other thing to check is whether the EET download is complete. It is a very large zip archive, so make sure there is no error (around 213MB).

**Comment by noderministicsingularity** [comment]
yes. i had a feeling it might be something like that. i decided to delete everything (backup archive too) and redownload everything from scratch. and i'm gonna do it on 2-3 other computer too to see if it happen aloot or just ocasionaly.
