### ISSUE TITLE
not downloading latest updated mods

### ISSUE THREAD

**Issue by AjlaaSS** [EE-Mod-Setup/EE-Mod-Setup#112]
I did not paid attention on other mods versions, only on SCS and Ascension, Install Tool download SCS 35.4 (while latest is 35.10), and Ascension 2.0.23 (latest is 2.0.28).

Also there is no way to install following mods :

wizard slayer rebalancing v114
ulrient saga
the white queen
tangle isle
tales of deep gardens
subtled spell tweaks
southern edge
Ruad
innershade
I shall never forget
Foundling

Install Tool offers these mods, but than says it can't download them. After providing them manually, Install Tool still claim it cannot download them despite I provide them manually (it accept them fine, do not require to Force them).

Could it be updated? At least to get latest SCS and Ascension. Thanks Roxxane.

**Comment by RoxanneSHS** [comment]
Updated the two mods (no effect, since the tool does not support Swedish language installation anyway...)
The download issue with those other mods must be a local issue with your connection to Dropbox, obviously something in your connection blocks it.
