### ISSUE TITLE
Documentation: Installation order for EE-Mod-Setup?

### ISSUE THREAD

**Issue by rubyFeedback** [EE-Mod-Setup/EE-Mod-Setup#113]
Installation order for EE-Mod-Setup? I assume it should go first. Could the readme 
confirm this?

**Comment by RoxanneSHS** [comment]
It is a tool used to install mods, it is not something to be installed itself. You unzip it and start it outside of the game directory with Start EE Mod Setup.vbs, just like stated in the readme pdf-document.
