### ISSUE TITLE
Wilson Chronicles 2.1 & Stone of Askavar 2.2 no longer available.

### ISSUE THREAD

**Issue by SomeGuyDoinWork** [EE-Mod-Setup/EE-Mod-Setup#115]
v 2.3 and 2.4 available from dropbox
https://www.dropbox.com/scl/fo/tf3jf41cmsbw4rcq4v4ui/AKJzm1QD8VJPaRKdI01x6qI/WILSON%20CHRONICLES?dl=0&rlkey=84ojtmkxqom9vt7ez398mm9mr&subfolder_nav_tracking=1

Stone of askavar is updated to 2.4.

**Comment by RoxanneSHS** [comment]
Updated
