### ISSUE TITLE
Some mod download validations appear broken.

### ISSUE THREAD

**Issue by SomeGuyDoinWork** [EE-Mod-Setup/EE-Mod-Setup#116]
Several mods appear to have broken verification. I looked at other issues and tried following those steps but I'm still getting this error.

The download links are fine and the files download file, its just the setup tool doesnt recognize them.

I followed instructions to manually download and provide mods however that did not work either. For some reason it appears these mods are constantly being reset to unspecified despite a fresh install.

I tried: No VPN, No Antivirus, Fresh Install of setup tool, setting configs to read only.

My install location is C:/Games/GoG/*

I've attached the log aswell. 

The following mod(s) could not be downloaded:

   Eilistraee's Song: The Mod itself (unspecified)

   I Shall Never Forget: The Mod itself (unspecified)

   Innershade: The Mod itself (unspecified)
          
   Tales of the Deep Gardens: The Mod itself (unspecified)
       
   The White Queen: The Mod itself (unspecified)
        
   Journey to Whin Hill: The Mod itself (unspecified)
  
   Oozes Lounge: The Mod itself (unspecified)
         
   Southern Edge: The Mod itself (unspecified)
        
   Neera Banters for BG:EE: The Mod itself (unspecified)
   
   Wilson Chronicles: The Mod itself (unspecified)
          

[EE-Debug-Download.log](https://github.com/user-attachments/files/15722105/EE-Debug-Download.log)

**Comment by RoxanneSHS** [comment]
It seems like you try to install mods on a protected directory in games/gog on the original game. That causes all kinds of error. Always use a copy of the clean/unmodded game that you have on some fully accessible partition of your computer.

**Comment by SomeGuyDoinWork** [comment]
@RoxanneSHS I Copied both BG2 and BG to my docs, and put ee mod setup in a separte folder with a fresh install, still no dice. Same mods are erroring.

**Comment by SomeGuyDoinWork** [comment]
I FINALLY resolved this by setting the entire config directory to read only. Something was incorrectly writing the names to unspecified.

**Comment by SomeGuyDoinWork** [comment]
@RoxanneSHS Figured out what goes wrong - For some reason, those mods are being set to unspecified then overriding each other as unspecified in the mod downloads folder. And there names arent being updated properly.

**Comment by SomeGuyDoinWork** [comment]
For anyone else encountering this issue, the steps are:

You need to proceed with mod selection for EET and get to download page, download mods and exit when errors.
This is in order to generate mod.ini and get downloaded files. download manually any additional mods from listed links.

Once thats done, open mod.ini and edit all unspecified to downloaded file name.

Repeat for global mod configs.

Then set all edited files to read only.

**Comment by dargonbr** [comment]
Hi!
The files described as unspecified are the ones downloaded from dropbox. I have changed the .ini on global, in case you can use it on future updates.
[Global.zip](https://github.com/user-attachments/files/15887680/Global.zip)
Thanks for the mod!!

**Comment by RoxanneSHS** [comment]
All of this seem to be local issues from whatever settings you use on your machine. Not some global problem that the tool can adjust to.
