### ISSUE TITLE
Receiving "_Depend_SetModState could not deactivate" errors.  Please Help! 

### ISSUE THREAD

**Issue by BGLuv** [EE-Mod-Setup/EE-Mod-Setup#117]
Hello, ;-)
And thanks to all of you I have used EE-Mod-Setup to create my EET Installs for many years. Unfortunately I recently lost my HD and physically lost my backup thumb drives with all my beloved EET Installations.
When I Re-Downloaded the the setup file today the new EET installs are giving me this error right after I test the mod DL links and try to continue. When testing download links I noticed it says:

DLC Merger
https://www.dropbox.com/s/506xpdt75hpkqrn/A7-DlcMerger-master.zip?dl=1
Hint: The name or size of the download has changed (A7-DlcMerger-master.zip / 113686 > unspecified / 110420).
This should be an updated version.
Archive found (0.11 MB)

WeiDU 64-bit
https://www.dropbox.com/s/opixatf4352yl8g/weidu64.exe?dl=1
Hint: The name or size of the download has changed (WeiDU64.exe / 1364992 > unspecified / 1364992).
This should be an updated version.
Archive found (1.3 MB)

-Summary-
All selected downloads were found.
Finished.

But when its finished checking all the mods it shows:

The following mod(s) could not be downloaded:

*  DLC Merger: The Mod itself (unspecified)
          https://www.dropbox.com/s/506xpdt75hpkqrn/A7-DlcMerger-master.zip?dl=1

*  WeiDU 64-bit: The Mod itself (unspecified)
          https://www.dropbox.com/s/opixatf4352yl8g/weidu64.exe?dl=1

I can manually download these files from the links provided and copy them to the EE Mods Download folder. And then use "Provide" and "Select" them manually, but then I get the errors listed below and selecting "Retry" just gives me the same errors.

_Depend_SetModState could not deactivate 327 = DlcMerger = DLC Merger(-)

_Depend_SetModState could not deactivate 336 = WeiDU64 = WeiDU 64bit(-)

Please let me know if there is any other info that I could provide to help and BIG Thank You! in advance for your time.
Cheers!

**Comment by RoxanneSHS** [comment]
Maybe this helps https://github.com/EE-Mod-Setup/EE-Mod-Setup/issues/116#issuecomment-2154817116

**Comment by BGLuv** [comment]
Thanks for the quick reply... That's funny I was having the same issues with Weasels Colors of Infinity Series Mods. But unlike SomeGuyDoinWork I got around that by downloading them manually and copying them into the EE Mod Downloads folder. Then I would just manually "Provide", "Select" and "Force" them during the installation process. Which sounds like that was not working for him?

During the installation setup process I'm able to provide all the mods that are not  automatically downloading by providing them manually.
It's only the DLCMerger and WeiDU files where I'm receiving the "_Depend_SetModState could not deactivate" error, even when I provide the files manually.
________________________________

**Comment by BGLuv** [comment]
Hello again, The comment that  you replied to "#116" was not the issue that I was having. Were you able to reproduce the "_Depend_SetModState could not deactivate" errors for DLCMerger and WeiDU?
Thanks again for your time
________________________________

**Comment by RoxanneSHS** [comment]
Those are not errors but statements. If Weidu and DLC Merger are downloaded and extracted correctly, they will be used despite that message. If missing, the program cannot run.

**Comment by BGLuv** [comment]
So if you currently run the program you're not seeing this?
________________________________

**Comment by BGLuv** [comment]
I tried doing everything in comment #116 that you suggested and it seemed to clear up the issues with DLCMerger & WeiDU and then created a new issue with EET. And editing the .ini file will not correct it.
What happened... it always ran smoothly for me in the past and it seems really buggy now? I'm obviously not the only one having similar issues within the last month. Is it running for anyone without having to edit .ini files now?
This is really sad for me... Thanks for keeping it going for as long as you have.
Cheers!

________________________________
