### ISSUE TITLE
Here the chamges for game ini

### ISSUE THREAD

**Issue by juergenleimbach** [EE-Mod-Setup/EE-Mod-Setup#2]
Chaos Sorcerer kit conflict with Tome and Blood=C:A7-ChaosSorcerer(0):TomeAndBlood(0)
- Chaos Sorcerer kit conflict with Tome and Blood=C:A7-ChaosSorcerer(0):TomeAndBlood(0)

; Tome and Blood reflexive dependencies
-TnB Magus class needs armored casting=D:TomeAndBlood(2):TomeAndBlood(9)
+All components need main=D:TomeAndBlood(-):TomeAndBlood(0)
+TnB Magus class needs TNB core=D:TomeAndBlood(2):TomeAndBlood(0)
+TnB Revised Dragon Disciples class needs TNB core=D:TomeAndBlood(1):TomeAndBlood(0)
+TnB Favoured Soul class needs TNB core=D:TomeAndBlood(3):TomeAndBlood(0)
+TnB Sylvan Disciple class needs TNB core=D:TomeAndBlood(4):TomeAndBlood(0)
+TnB Revenant Disciple class needs TNB core=D:TomeAndBlood(5):TomeAndBlood(0)
+TnB Amorphous Disciple class needs TNB core=D:TomeAndBlood(6):TomeAndBlood(0)
+TnB Metamagic class needs TNB core=D:TomeAndBlood(11):TomeAndBlood(0)
+TnB Ability Score Bonuses class needs TNB core=D:TomeAndBlood(14):TomeAndBlood(0)

**Comment by RoxanneSHS** [comment]
Just added it some seconds ago, overlapping with this.
Can you please crosscheck that my latest update is correct?
