### ISSUE TITLE
Multiple errors during install

### ISSUE THREAD

**Issue by antoine-levitt** [EE-Mod-Setup/EE-Mod-Setup#22]
Hi,

I'm not sure this is the correct place to report this, so feel free to close if not. I chose a (I thought) relatively reasonable set of mods and tried to install, and got several errors during install. Here is the log: https://gist.github.com/antoine-levitt/017f4fc4706b5457fa47b58062ec7292

**Comment by RoxanneSHS** [comment]
I left a comment at your gist.
You try to mod directly in the protected original game and some files cannot be accessed there.

**Comment by antoine-levitt** [comment]
Thank you! I'm a linux user usually so am not familiar with windows's craziness. I changed it to another directory but it didn't help. In particular the following error:
```
ERROR: BIFF [.\DATA\PATCH24.BIF] cannot be loaded: Failure("read 0 of 54240 bytes from [.\\DATA\\PATCH24.BIF]")
ERROR: Failure("resource [BDCUTID.CRE] not found for 'COPY'")
Initialise AI components (required for all tactical and AI components) (Sword Coast Stratagems) was not installed due to errors.
```
seems unrelated. I've got a native (non-upgraded) 2.5 version, maybe that's why?

**Comment by antoine-levitt** [comment]
Of note, it says `"read 0 of 54240 bytes from [.\\DATA\\PATCH24.BIF]"` but my patch24.bif is 143mb

**Comment by RoxanneSHS** [comment]
Non-updraded mean what? You need 2.5.xxxx with SoD to install EET. The missing resource is an SoD file, you see the prefix BDxxxx which is used for everything related to SoD. You also need the DLC merger to unpack the SoD files prior modding - if you use the Install Tool then this is done automatically.
 

Sent: Sunday, September 27, 2020 at 8:57 AM

**Comment by antoine-levitt** [comment]
I think my installation was just corrupted, I started again from a fresh install and everything seems to work. Thanks for this very nice interface (I know how hard it is to design GUIs, and especially to handle gracefully  the caseswhen things go wrong, so I appreciate it very much!)
