### ISSUE TITLE
{Update} Please update the listed mod download links,failed to download.

### ISSUE THREAD

**Issue by 32394444** [EE-Mod-Setup/EE-Mod-Setup#23]
Keeping Yoshimo
Improved Archer Kit
Banter Accelerator for Enhanced Edition games
Chaos Sorcerer Kit
Spellsword Custom Kit (New)
Golem Construction for Spellcasters
Trials of the Luremaster
Ajantis BG1 Expansion
Ajantis NPC for BG2
All Things Mazzy (New)
Animus: Sentient Weapon
Ascension
Boards o' Magick Item Pack
Chloe NPC
CoM Encounters
Cowled Menace (New)
Unholy Gate Opening Ritual Book 
Send NPCs to an Inn
Tactics EE
Eternal Imoen
Full Plate and Packing Steel
igi's Spell System Adjustments (New)
Jan's Extended Quest (New)
Lucy the Wyvern
Petsy Chattertone NPC
Rjali Romance (New)(All link Failed)
Ulrien Of Cormyr, Saga Master
Sarevok Romance
Varshoon an Illithid NPC
Wizard Slayer Rebalancing

**Comment by RoxanneSHS** [comment]
The links work, just tested. It is either a local issue or some firewall setting prevents connection with certain addresses.
