### ISSUE TITLE
Please make a option that could change the size of font in entries. Eyes really hurt.

### ISSUE THREAD

**Issue by 32394444** [EE-Mod-Setup/EE-Mod-Setup#24]
Just the title said, got really tired to catch up the extremely small font that used in EE Mod setup tool, please make a option that could adjust the font size please.

**Comment by RoxanneSHS** [comment]
Extract this file to the BWS_EE/App/Includes folder to overwrite the existing file, then start with new configuration.
[08_GUI.zip](https://github.com/EE-Mod-Setup/EE-Mod-Setup/files/5536870/08_GUI.zip)

Note - that SW changes for the old tool are no longer made but configuration files may be changed individually.
