### ISSUE TITLE
seems it can't find my saved game

### ISSUE THREAD

**Issue by sdelanoue** [EE-Mod-Setup/EE-Mod-Setup#27]
I installed Both Baldur's gate 1 EE and Baludr's gate II  EE v 2.6 via Steam, copied the 2 dirs to F:\BGTEE

the started both games in English and save game for BG1 BG2 and TOB

the started EE MOD Setup tool with Update EE Mod Setup.vbs but it show me the following error :
Please start the game, choose the language you like, start and create a savegame

I'm using Win 10 20H2

[EE-Debug-Link.log](https://github.com/EE-Mod-Setup/EE-Mod-Setup/files/6369480/EE-Debug-Link.log)
[EE-Debug-FileCheck.log](https://github.com/EE-Mod-Setup/EE-Mod-Setup/files/6369481/EE-Debug-FileCheck.log)

**Comment by RoxanneSHS** [comment]
I assume that drive F is some external drive? It is possible (depends on
your local configuration) that your drive that contains the saves and
configuration files is in C: or D: and hidden?
Try this: Go to your documents folder (of your user id) and look for
folders Baldur's Gate II - Enhanced Edition and Baldur's Gate - Enhanced
Edition, copy them to F.

These issues are hard to analyse without knowing your local configurations
and settings, so I can only guess...

**Comment by sdelanoue** [comment]
I found the source of my issue:
My user account is not an admin one  so when I run the program as admin it doesn't acces my Documents folder.
 I solved it by logging on my admin account and move his documents folder in same location as my limited user

now working fine
