### ISSUE TITLE
some issue in French installation

### ISSUE THREAD

**Issue by sdelanoue** [EE-Mod-Setup/EE-Mod-Setup#29]
Hi
I installed BG1 EE & BG II EE 2.6 with Steam on a Win 10 x64 pro Fr

I made a directory in local drive F: named BGTEE
Then copied the 2 games on it

I started both to configure them in English and save a game

I used EE Mod setup script "Update EE Mod Setup.vbs", selected language as En only
Then I used attached BWS-Phane-Selection.ini file for mod selection

All work fine, got SCS and EET Menu fine

Then I wanted to play in French

So I made a directory in local drive F: named BGTEEFR
Then copied the 2 games on it

I started both to configure them in French and save a game, event stared the EET I installed before in English to configure it in French

I used EE Mod setup script "Update EE Mod Setup.vbs", selected language as FR only
Then I used attached BWS-Phane-Selection FR.ini file for mod selection

But Sword Coad Stratagem fail, I made a report here on their website
https://www.gibberlings3.net/forums/topic/32694-error-when-installing-in-french-no-translation-provided-for-40402/

After their answer I tried to install it again with EE Mod but at first error I replaced it with latest download version and selected retry but it complain that is shall be installed after EET
So try again not installing SCS with EE Mod setup but to install it separately: SCS install well

But got a second issue with SCS installed or not :
When I start the game I got same loading screen as BG2 EE alone, the selection of the game/mod instead of the one I got in English EET

When I start Shadow of Amn I can load a game I started EET English, but if I select start a new game I come back directly to first screen (selection of the game)
So I tried to install EET Alternative GUI (SOD) [FR] but got directly the menu for Black pit 2 only

So cannot start a new game for EET, only load one.
I attached the log on the Fr game installed without SCS or EET Altenative GUI
[EET.zip](https://github.com/EE-Mod-Setup/EE-Mod-Setup/files/6441485/EET.zip) for all mentioned files

regards,
Stéphane

**Comment by RoxanneSHS** [comment]
You missed to install a patch that is required for the SoD Gui with game
version 2.6 as mentioned here
http://baldursextendedworld.com/Vanilla_Forums/discussion/comment/12493/#Comment_12493.
The Install Tool has it under headline "Corrections".

Try this
- Uninstall SoD Gui manually
- Download this https://www.dropbox.com/s/n1lw6kl7unzo6uj/EET_SoD26.zip?dl=1
- Extract it to BG2EE where you have EET and run
setup-EET_26_SoD_Guipatch.exe
- Install SoD Gui again
Hopefully it fixes the problem.

**Comment by sdelanoue** [comment]
ok for the menu thanks, but about Sword coast stratagems ?

**Comment by RoxanneSHS** [comment]
The status of SCS in the new 2.6 version is unknown. There can be any
number of issues that need to be solved. If a component gives you an error,
it may be best to skip it. SCS is a complex mod that may take a long time
to be updated for the new version, however much of it may still work still.

**Comment by sdelanoue** [comment]
I did the install from the beginning adding the missing addon that I thought it was imported when I first loaded the .ini from En in the Fr config and did deselected SCS
but still an issue with the menu
So I tried your manual procedure and no change

**Comment by sdelanoue** [comment]
[EET.zip](https://github.com/EE-Mod-Setup/EE-Mod-Setup/files/6443697/EET.zip)
I join you le .ini and log of last failed install

**Comment by RoxanneSHS** [comment]
I wonder how you do the installation without ~EET_FIX/EET_FIX.TP2~ #0 #0 // EET Fix: v1.2
It does not appear in your ini file at all, not even in de-save mods. Means that you manipulate the tool to fail by removing mandatory elements.

**Comment by sdelanoue** [comment]
because it is not present if you select only Fr, I now made Fr 1rst En 2nd and see it selected as [EN]

And it WORKS !!! Thanks a lot

**Comment by RoxanneSHS** [comment]
Thank you for that information. There is a logic flaw in the tool here...the fix adds some lines of text which are only in EN - but it is required for all languages, so it needs to be "neutral".
