### ISSUE TITLE
Couldn't be downloaded mods

### ISSUE THREAD

**Issue by Anprionsa** [EE-Mod-Setup/EE-Mod-Setup#3]
Haer'Dalis' Swords: The Mod itself (HaerDalisSwords_v2.zip)
          http://www.shsforums.net/index.php?app=downloads&module=display&section=download&do=confirm_download&id=804
   Aerie in BG:EE: The Mod itself (BG1AerieV11.rar)
          http://www.coutelier.org.uk/files/BG1AerieV11.rar
   Wizard Slayer Rebalancing: The Mod itself (wsr_v113.exe)
          http://www.shsforums.net/files/download/960-wizard-slayer-rebalancing-v110-windows-version/
   IEP Extended Banters: The Mod itself (IEP Banters v5.4.zip)
          http://www.shsforums.net/files/download/558-iep-extended-banters/
   aTweaks: The Mod itself (atweaks-v453.zip)
          http://www.shsforums.net/files/download/949-atweaks-platform-independent/
   Mazzy Friendship: The Mod itself (Mazzy Friendship v3.2.zip)
          http://www.shsforums.net/files/download/712-mazzy-friendship-soa-tob/
   Isra NPC: The Mod itself (isra_v2.2.zip)
          http://www.shsforums.net/files/download/1042-isra/
   Adrian NPC: The Mod itself (adrian_v4.3.zip)
          http://www.shsforums.net/files/download/1007-adrian/
   Afaaq, the Djinni Companion: The Mod itself (DjinniCompanion-master.zip)
          https://lynxlynx.info/ie/modhub.php?Argent77/DjinniCompanion&master
   Isra BG2 NPC: The Mod itself (Isra_bg2_v3.zip)
          http://www.shsforums.net/files/download/1070-isra-bg2-pc/
   Skie, the Cost of One Girl's Soul: The Mod itself (Skie Cost v1.2.zip)
          https://www.dropbox.com/sh/56dr4q8h2q7djri/AAAKgyoVdxJIKIjvbuXP_spXa/SKIE%20-%20THE%20COST%20OF%20ONE%20GIRL%27S%20SOUL/Skie%20Cost%20v1.2.zip?dl=1
   Lucy the Wyvern: The Mod itself (lucy-v4a.exe)
          https://www.dropbox.com/s/m3m72ps2n11wmhp/lucy-v4a.exe?dl=1
   Nephele: The Mod itself (NepheleEET-master.zip)
          https://www.dropbox.com/s/atenvzkqia3po0z/NepheleEET-master.zip?dl=1
   Eilistraee's Song: The Mod itself (Eilistraees Song v6.6.zip)
          https://www.dropbox.com/sh/56dr4q8h2q7djri/AADAw5j6a06ScrJg84tvizS2a/EILISTRAEE%27S%20SONG/Eilistraees%20Song%20v6.6.zip?dl=1
   The Sellswords: The Mod itself (Sellswords-master.zip)
          https://www.dropbox.com/s/fgbc034vwrgxe5g/Sellswords-master.zip?dl=1
   Isandir's Portrait Pack: The Mod itself (ISANDIRS_PORTRAIT_PACK.7z)
          https://www.dropbox.com/s/dqw52l3jl7nqvls/ISANDIRS_PORTRAIT_PACK.7z?dl=1
   Thrown Hammers: The Mod itself (Sampsca-ThrownHammers-v6.0.3-0-gb49bb57.zip)
          http://lynxlynx.info/ie/modhub.php?Sampsca/ThrownHammers&pre
   Region of Terror: The Mod itself (master.zip)
          https://github.com/weigo87/RoTerror-EE/archive/master.zip
   IWDification: The Mod itself (master.zip)
          https://github.com/Gibberlings3/iwdification/archive/master.zip
   Shadow Magic (NEW): The Mod itself (master.zip)
          https://github.com/ArtemiusI/Shadow-Magic/archive/master.zip

**Comment by RoxanneSHS** [comment]
Here is a new alternative link
https://www.dropbox.com/s/v04bbstjhiqh8k5/BG1AerieV11.rar?dl=1

The ones on Spellhold SHS are down as long as the site it not operating.

I checked all others and found them working
