### ISSUE TITLE
The Wheels of Prophecy not listed for EET install.

### ISSUE THREAD

**Issue by JesseRMeyer** [EE-Mod-Setup/EE-Mod-Setup#30]
Hi, thanks for the great tool.

Is The Wheels of Prophecy mod not supported in the EET configuration?  I am trying to install it, but it is not listed.

Thanks

**Comment by RoxanneSHS** [comment]
The mod has not been updated by the author for the new Ascension version.
Instead most of the content is now covered by a separate Ascension component "Balthazar can be redeemed".
(You may have seen some update attempt for WoP posted somewhere but that version is not by the author which is the same one who wrote Ascension itself.)

**Comment by JesseRMeyer** [comment]
Hi,

I see there some some logic handling "Wheels of Prophecy" in the code base.  

https://github.com/EE-Mod-Setup/EE-Mod-Setup/blob/5abf05ce83e6a5596571b69c8f9c5f55f1188724/App/Includes/07_Extract.au3#L906

I am wondering if I can leverage this -- Is there a way to override the installation process to manually install a mod that is not otherwise listed?  I understand your preferences but I have my own.  The mod must be installed before other mods I install with EE Mod Setup Tool.

Thanks.

**Comment by RoxanneSHS** [comment]
The rational for suspending the mod is still the one in the answer above. Nothing has changed in the meantime.
You can always manually set a "pause" in the installation process (you can pre-select it in the mod tree if you know what the next selected mod in sequence is). During pause you can install a mod with its setup-xxxxx.exe, (leave the tool open), then continue automatic installation.
Anyway, I have received other reports from players who got stuck in ToB with that mod, so be warned.

**Comment by RoxanneSHS** [comment]
You either get pause 
- when you right click on a mod name during selection of mods > the tool will automatically pause prior to the selected mod (may be selected multiple times).
- any time during mod installation running - note that the tool will finish with the current mod(component) before stopping.
