### ISSUE TITLE
CLINK breaks ChangeDirectory function

### ISSUE THREAD

**Issue by journeym** [EE-Mod-Setup/EE-Mod-Setup#31]
Im using CLINK, and it has never caused any problems, even in ProjectInfinity :)
https://github.com/mridgers/clink

After really long retry count of installing my list of mods, i managed to pinpoint this to CLINK.
After uninstallation everything went fine, before that there was an error

CLINK G:\BG1>Error during changing into directory G:\BG1.
Exiting due to major problems.

Im no expert on autoit, but looking through Func _Process_ChangeDir, it seems the process doesnt get the expected value form consoleoutput.
Well, in any case, if anyone else gets this, they'll now what to do.

**Comment by RoxanneSHS** [comment]
I assume this is with an EET installation?

I suspect that your tool manipulates CMD behaviour and output.

CMD;REM;EET;--- DO NOT MODIFY THIS LINE: this switches to BG2:EE folder for EET installs (special case handled in Install.au3 and Testing.au3) ---

or simply, you make changes to a SW and it does no longer work...
