### ISSUE TITLE
Mod Download Renaming

### ISSUE THREAD

**Issue by Duneathor** [EE-Mod-Setup/EE-Mod-Setup#33]
Several mods download with the same name (i.e. master.zip)
Consider renaming so that they don't get clobbered and have to be manually downloaded and selected

**Comment by RoxanneSHS** [comment]
The issue is on the sending end while my tool is the receiver. Here are some details

https://baldursextendedworld.com/Vanilla_Forums/discussion/comment/11608/#Comment_11608
