### ISSUE TITLE
Install Tool - Download Issues

### ISSUE THREAD

**Issue by dla12345** [EE-Mod-Setup/EE-Mod-Setup#34]
For some reason, this install tool is having a major problem recognizing mods that have already been downloaded,. I've tried to start a new install half a dozen times and I can't get past the install section with all of my selected mods, because for some reason the tool will show that several mods failed to download, even though they did.

Okay fine. I can force it right? Not for all of them. For some reason, I'm only allowed to force a few of them to be recognized. The mod will pick two or three mods and will not give me the option to force the mods to be recognized, even though they've already been downloaded.

The worst part is that each install attempt will lead to a new set of mods that "failed to be downloaded", even though some of those mods were recognized in the previous attempt. So it's not like it's a problem with the mod, but a problem with the install tool. 

I just don't get it. I didn't have this problem a couple of weeks ago, and now, all of a sudden, the install tool is having these issues.

[EE-Debug-Download.log](https://github.com/EE-Mod-Setup/EE-Mod-Setup/files/8498341/EE-Debug-Download.log)

[EE-Debug-Download.log](https://github.com/EE-Mod-Setup/EE-Mod-Setup/files/8498343/EE-Debug-Download.log)

[EE-Debug-Download.log](https://github.com/EE-Mod-Setup/EE-Mod-Setup/files/8498344/EE-Debug-Download.log)

Can this be fixed please?

**Comment by RoxanneSHS** [comment]
The problem is random and not originating in the tool but by mods hosted on github. They are sometimes just appearing as master.zip instead of xxxxmod-master.zip and when it happens more than once, the later one overwrites the previous.
https://baldursextendedworld.com/Vanilla_Forums/discussion/comment/13729#Comment_13729

**Comment by dla12345** [comment]
If that is the case, then why is the tool not letting me select the mods and force them to work? I understand if the tool is having trouble with all of the -master.zip files, but when it gives me the option to select, shouldn't I actually be able to select the mods and force it to work? In those log files, I'm only able to force a few to work. The others, as soon as I hit select, locate the file, and hit enter, it immediately goes to the next mod completely skipping the "force" step. Then when I'm done selecting, and forcing the files that I can, all the one where the force option didn't show up are listed as missing, even though I have the mods already downloaded.

**Comment by dla12345** [comment]
Also, I've done this mod install setup several times before with little variations (once a couple of weeks ago), and I've never run into this problem before to this degree. There's only ever been two mods that I've had to force. The Weasel Mod and the Wizard Slayer Rebalance mod. All the other mods downloaded perfectly.

Now its like 10 more mods on top of those, but they are all completely random and they change from install attempt to install attempt.

**Comment by RoxanneSHS** [comment]
What you can do (like you say, it is a random issue and it happens on certain days and connections) is this
- put mod zip or rar files you already have into a separate directory outside the tool downloads
- hit the "x" in front of the active download for such a mod to skip the repeated download
- later point the missing mod to your saved location

**Comment by waebbl** [comment]
AFAICS the downloaded file is saved under a different name than the filename on GitHub[1], using the `--output-document=` option to `wget`. How does it actually happen, that the files are sometimes saved as `master.zip`? IMO that's not possible, if the command is executed correctly, no matter how the files are named on the server.

Could it be, the filename is sometimes saved incorrectly in the `$p_File` variable? This variable is passed to the `_Net_DownloadStart` function and is also used in other contexts as it seems (though I might be wrong on the latter, being able to somehow decipher AutoIt, but I'm not fluent with it and to the code structure). Is it possible that, e.g. from a previous query of the file, this variable sometimes has a value of `master.zip` and thus saves it under an incorrect name?

[1] https://github.com/EE-Mod-Setup/EE-Mod-Setup/blob/master/App/Includes/11_NET.au3#L620 and L622

**Comment by RoxanneSHS** [comment]
You are probably right with saying that the name is overwritten with the new value. The question remains where the new value came from in the first place. The code is not mine but part of the open source license the tool uses. I am not familiar with the old coding language myself, so I am in no position to change something here. I try to keep the whole thing working on the basis of maintaining the dynamic configuration files and trying not to break the core of it.

**Comment by dla12345** [comment]
> What you can do (like you say, it is a random issue and it happens on certain days and connections) is this
> 
>     * put mod zip or rar files you already have into a separate directory outside the tool downloads
> 
>     * hit the "x" in front of the active download for such a mod to skip the repeated download
> 
>     * later point the missing mod to your saved location

Hello Roxanne,

So i tried again today. Same issue.

There are a few common mods that pop up needing to be pointed to, Weasels, WSR, and Tangled Oak. However, apart from those, another 3-10 other mods that will pop up which I will be unable to point to or force. Those additional mods are random from install attempt to install attempt, minutes apart from each other. Sometime the EET Master fails to load and can't be forced. 10 minutes later & Next Install attempt, EET Master works, but BGEE Classic Movies doesn't, even though it worked the first time. 10 more minutes later & third install attempt, both EET Master and BGEE Classic Movies work, but now several quests mods don't work. Each attempt a new selection of mods are unable to be downloaded, selected or forced, even though I literally have all of the mods already downloaded in separate folders.

I can't follow your suggestion because there is no way to know which mods will fail in any given install attempt. I'd have to cancel them all, and point each and every mod to the backups that I have, but that would be dozens upon dozens of mods and, even then, there is no guarantee that I wouldn't run into the same problem where the install tool doesn't recognize my selection or allow me to force them to work.

Do you know why the tool wouldn't be able to recognize that I selected the mod that it is asking for? The tool not recognizing that I've selected the mod it's asking for is, to me, the biggest issue.

**Comment by Duneathor** [comment]
See attached hacked patch.
If you have already downloaded everything....
[11_NET.au3.patch.txt](https://github.com/EE-Mod-Setup/EE-Mod-Setup/files/8527660/11_NET.au3.patch.txt)

This is more of a temporary hack than anything long term

**Comment by RoxanneSHS** [comment]
@Duneathor
Do you have some idea about a code update that I could include and test with?
The main issue is that this check for mod versions etc was made for old hostings at the mod sites back then. It does not make much sense in the the github world anymore because the pre-requisites have changed. Best way would be to get rid of it without destroying the rest of the code. Since I am no coding expert for this, I have stayed away from it so far.

**Comment by Duneathor** [comment]
Yes. I am testing a patch to disable server side renaming, so whatever the filename is in the config will be the file name of the download.

**Comment by RoxanneSHS** [comment]
> Yes. I am testing a patch to disable server side renaming, so whatever the filename is in the config will be the file name of the download.

Good to know. I had the idea before but not the skills to do it. I made an attempt once but introduced some bugs with it. But the concept should be fine - the renaming idea was from another age with other hosting sites and not needed today.

**Comment by myevilmode** [comment]
@Duneathor 
How to install this patch?

**Comment by Revan7even** [comment]
I'm having the same issue where [Dark Horizons Tweaks](https://github.com/RoxanneSHS/DarkHorizonsTweaks/archive/master.zip) downloads as DarkHorizonsTweaks-master.zip but the install tool expects "master.zip", however a "master.zip" already exists in the download folder from another mod.

**Comment by RoxanneSHS** [comment]
The issue can happen randomly with any mod downloaded from github. However, for those two mods I can provide another download link in the tool now since they are stable and do not necessarily need to be hosted at github.

**Comment by noderministicsingularity** [comment]
i have detailed a solution to manualy rename the offending files here; https://www.nexusmods.com/baldursgate2ee/mods/61   its not really a fix , its just you manipulating the files to make them behave as intended. but its a start.  i think i remember posting this on your previous forum before it was closed down, but its a prety straightforward edit.   i am also not good enough to autimatise this, say, with a .bat command file, but it could probably be done with minimal effort.

**Comment by RoxanneSHS** [comment]
I have recently identified a number of (now stable) mods with dedicated releases that will be used instead of "master". I will continue to research for such mods - that will not eliminate the issue but reduce the probability of occurrence.

**Comment by noderministicsingularity** [comment]
thats awesome. thank you for your continued hard work on your project.
