### ISSUE TITLE
How can I check which modes successfully installed? 

### ISSUE THREAD

**Issue by apredeus** [EE-Mod-Setup/EE-Mod-Setup#36]
Hi, 

Thank you for this nice tool. I was wondering if there's a way to check which components were successfully installed? 

Thank you

**Comment by RoxanneSHS** [comment]
Open the file weidu.log with any text editor, the file is in your game directory and lists all components in the order they were installed. In case of EET, there is a file WeiDU-BGEE.log as well, those are the mods installed on BG1 and then imported by EET.

**Comment by apredeus** [comment]
So if that's all that's listed there, does this mean my install mostly failed? (I've selected about 50 different mods I think):

> // Log of Currently Installed WeiDU Mods
> // The top of the file is the 'oldest' mod
> // ~TP2_File~ #language_number #component_number // [Subcomponent Name -> ] Component Name [ : Version]
> ~SETUP-WEIDU.TP2~ #0 #0 // 24700
> ~AREA_PATCHER/SETUP-AREA_PATCHER.TP2~ #0 #0 // Area Patcher: ALPHA 16
> ~AREA_PATCHER/SETUP-AREA_PATCHER.TP2~ #0 #2001 // Fix AR2300 Script - Prevent infinite loop after Sahuagin king dies: ALPHA 16
> ~AREA_PATCHER/SETUP-AREA_PATCHER.TP2~ #0 #2003 // Fix AR0406 Script - Remove Lord Jierdan from Copper Coronet after Windspear Hills battle: ALPHA 16
> ~ITEM_PATCHER/SETUP-ITEM_PATCHER.TP2~ #0 #0 // Install Marker: ALPHA 6
> ~ITEM_PATCHER/SETUP-ITEM_PATCHER.TP2~ #0 #100 // Gives some vanilla items the Droppable Flag: ALPHA 6
> ~ITEM_PATCHER/SETUP-ITEM_PATCHER.TP2~ #0 #103 // Gives some Huple items the Droppable Flag: ALPHA 6
> ~ITEM_PATCHER/SETUP-ITEM_PATCHER.TP2~ #0 #104 // Gives some Iylos items the Droppable Flag: ALPHA 6
> ~ITEM_PATCHER/SETUP-ITEM_PATCHER.TP2~ #0 #105 // Gives some Keto items the Droppable Flag: ALPHA 6
> ~ITEM_PATCHER/SETUP-ITEM_PATCHER.TP2~ #0 #106 // Gives some Kim items the Droppable Flag: ALPHA 6
> ~ITEM_PATCHER/SETUP-ITEM_PATCHER.TP2~ #0 #107 // Gives some Kivan and Deheriana items the Droppable Flag: ALPHA 6
> ~ITEM_PATCHER/SETUP-ITEM_PATCHER.TP2~ #0 #108 // Gives some Lena items the Droppable Flag: ALPHA 6
> ~ITEM_PATCHER/SETUP-ITEM_PATCHER.TP2~ #0 #110 // Gives some Ninde items the Droppable Flag: ALPHA 6
> ~ITEM_PATCHER/SETUP-ITEM_PATCHER.TP2~ #0 #113 // Gives some Tashia items the Droppable Flag: ALPHA 6
> ~ITEM_PATCHER/SETUP-ITEM_PATCHER.TP2~ #0 #117 // Gives some Aeon items the Droppable Flag: ALPHA 6
> ~ITEM_PATCHER/SETUP-ITEM_PATCHER.TP2~ #0 #118 // Gives some Amber items the Droppable Flag: ALPHA 6
> ~ITEM_PATCHER/SETUP-ITEM_PATCHER.TP2~ #0 #119 // Gives some Angelo items the Droppable Flag: ALPHA 6
> // Recently Uninstalled: ~SETUP-BWS_FINAL.TP2~ #0 #0 // Make quick-logged WeiDU-entries visible

**Comment by RoxanneSHS** [comment]
According to your log, no mods were selected, just a few patches by the tool were made. There are two possibilities, a)you ran the tool multiple times and the last log has overwritten the "real" log (in this case there may be other xxx.log files in your directory) or b) you made some mistake in handling the tool (there is a pdf file in the documents part of the download package with detailed instructions).
