### ISSUE TITLE
error installing EET

### ISSUE THREAD

**Issue by phoenixred80** [EE-Mod-Setup/EE-Mod-Setup#37]
I get the following error when installing
ERROR: [EET/SOD_GUI/CH01AJON.MOS] -> [EET/SOD_GUI/CH01AJON.MOS] Patching Failed (COPY) (Unix.Unix_error(20, "stat", "EET/temp/biff/mos1324.pvrz"))
ERROR: Unix.Unix_error(20, "stat", "EET/temp/biff/mos1324.pvrz")
Enhanced Edition Trilogy (Enhanced Edition Trilogy) was not installed due to errors.

it is a fresh install from GoG v2.6.6, copied to a separate folder and I have not added any other mods

**Comment by RoxanneSHS** [comment]
Check that you have full access rights as administrator. Also see if the EET-master.zip is completely downloaded, it is a large file 271MB and can occasionally fail. (The missing file should be in EET/base/gui/sod, see if it is there.)

**Comment by glavin99** [comment]
how can i get the full file. mine stops at 27MB

**Comment by RoxanneSHS** [comment]
Try the direct link https://github.com/Gibberlings3/EET/archive/refs/heads/master.zip. If finished, do not forget to put the archive into the tool's download folder. (Alternatively, you may unpack EET and install it manually but then you have to install other mods manually as well.)

**Comment by glavin99** [comment]
Like that?


***@***.***

**Comment by glavin99** [comment]
Hi

I love this game. I have always wanted more.

Thanks for your efforts.

Dave

**Comment by glavin99** [comment]
ERROR: illegal 2-byte read from offset 658 of 658-byte file EET/TEMP/PATCH/ITM/CMSTQ04.ITM
ERROR: [EET/TEMP/PATCH/ITM/CMSTQ04.ITM] -> [EET/TEMP/PATCH/ITM/CMSTQ04.ITM] Patching Failed (COPY) (Failure("EET/TEMP/PATCH/ITM/CMSTQ04.ITM: read out of bounds"))
ERROR: Failure("EET/TEMP/PATCH/ITM/CMSTQ04.ITM: read out of bounds")
Enhanced Edition Trilogy (Enhanced Edition Trilogy) was not installed due to errors.


dammm

**Comment by RoxanneSHS** [comment]
This is not really related to the Install Tool but an error between EET and your game version. Either your base game has some corruption or the download of the EET archive is not complete. The failure is in some weidu operation that is just started by the tool at the given time but not influenced by it in any way.
Did you try to install EET manually to see if the error repeats?

**Comment by glavin99** [comment]
Hmmm

Story of my life.

I will try that.

I have the steam version of BG EE 1 and 2

Thanks.

If there is way, I can compensate you for your time let me know.

Dave

**Comment by RoxanneSHS** [comment]
Note that for the steam version you need to run the dlc-merger in BGEE prior to running EET in BG2EE. This is to unpack the SoD module for modding. (In automated mode, the Install Tool takes care of that.)

**Comment by glavin99** [comment]
Thank you so much.

**Comment by phoenixred80** [comment]
> Check that you have full access rights as administrator. Also see if the EET-master.zip is completely downloaded, it is a large file 271MB and can occasionally fail. (The missing file should be in EET/base/gui/sod, see if it is there.)

Ran the update vbs through elevated command prompt. Deleted the EET-master.zip and manually downloaded it (it was the same size 271MB). Still same issue

**Comment by RoxanneSHS** [comment]
Just to be sure, you have BGEE + SoD extension and BG2EE and all is 2.6?

**Comment by phoenixred80** [comment]
Sorry I am taking time to come back to you. I have a 2 month old and the whole copy/paste operation of all the game files even with an M2 SSD takes too much time in between fresh attempts.

I verified I have BGEE + SOD + Black Pits and BG2EE. Both games show version 2.6.6

I have done an install using GOG Galaxy, ran both games once and exited. This is my base. I make a copy of the game folders to C:\BGT\ every time I make a new test.

**Comment by phoenixred80** [comment]
[EE-Debug-Installation.log](https://github.com/EE-Mod-Setup/EE-Mod-Setup/files/9331183/EE-Debug-Installation.log)

this is the log file from last time

**Comment by RoxanneSHS** [comment]
Since it is a local error, see if there is a folder SoD_GUI created in the EET folder in your BG2EE directory. Within that should be some mos files, including CH01AJON.MOS. The last is the file that the installation finds missing.
The subfolder is created during EET setup and files are copied into it during EET process. If it is missing, then something prevents the operations on your computer.

**Comment by phoenixred80** [comment]
There is a file in that directory, 52 bytes in total

**Comment by RoxanneSHS** [comment]
You can download this https://www.dropbox.com/s/zshtpkv649junm2/CH01AJON.zip?dl=1 and extract and replace it to see if that file was corrupted. The error log says that EET cannot patch that file.

**Comment by glavin99** [comment]
Hi

I appreciate your time. Mine are grown and bumming money. Lol


Thanks.




Dave



Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by glavin99** [comment]
The stupid me thanks you more

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by glavin99** [comment]
Success.

I'm in the mod version

Thanks for your help

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by glavin99** [comment]
Hi

Sorry I am a stupid tech.

Where is the tools download folder?

I would be happy to pay for your help.

Dave

**Comment by glavin99** [comment]
Im just downloaded a cracked version… I bought it already…

Im gonna try the patch on that.

If I can’t get it working how much for you to remote in and do it. 😊

Dave

**Comment by glavin99** [comment]
I think this is it?

***@***.***
