### ISSUE TITLE
New Mods for IWDEE

### ISSUE THREAD

**Issue by Timbo0o0o0** [EE-Mod-Setup/EE-Mod-Setup#39]
Hi Roxanne,
could you please add the following mods to the Install Tool for IWDEE:

NPC & Quest:

https://forums.beamdog.com/discussion/82650/mod-hommet-npc-for-iwd-ee-thread-includes-sword-coast-legends-spoilers

https://forums.beamdog.com/discussion/82596/mod-lanna-npc-for-iwd-ee

https://forums.beamdog.com/discussion/85092/mod-snowytoes-hamlet

EEX:

https://forums.beamdog.com/discussion/71798/mod-eeex-v0-9-7-alpha

https://forums.beamdog.com/discussion/68958/mod-bubbs-spell-menu-v4-4/p9

UI:

https://github.com/artyfox/DragonspearUI/archive/refs/heads/iwd.zip

(This is a fork of the famous)

https://forums.beamdog.com/discussion/50357/mod-dragonspear-ui-v2-42/p1

(This is the original)

https://github.com/anongit/DragonspearUI/archive/refs/heads/master.zip

(This is with the fix for 2.6)

Thank you so much for all your help!
Have a nice day and best wishes,
Timbo

**Comment by RoxanneSHS** [comment]
Status:
1. The 3 IWD mods have been added, however I have not tested them.
2. Tobex or EEX is not supported (this is for all games not just IWD)
3. The Install Tool supports v22.01.3 of DragonspearUI (the one with the fix for 2.6) for BG games. It has not been configured yet for IWDEE. In case this is the version that should also be used for IWDEE, the change can be made. Let me know, I can do this but you will need to test it yourself to see if it all works.

**Comment by Timbo0o0o0** [comment]
Thanks a lot!

https://github.com/artyfox/DragonspearUI/archive/refs/heads/iwd.zip

is the version from "Artyfox" from the beamdog forum.
It's the newest Version especially for IWDEE.
https://forums.beamdog.com/discussion/comment/1188260/#Comment_1188260


Do you think there will be EEX support in the future?

**Comment by Timbo0o0o0** [comment]
Oh, I understand. Is it possible to add the normal Version for 2.6 then? I could rename the one by Artyfox and put the archiv into the download folder and force the installer to use this version. Did you meant thar with "rename the clone"?
I did that when there were newer versions of mods available and it mostly worked.

**Comment by RoxanneSHS** [comment]
That is a different story...
Try this procedure
In the mod selection tree right click on one of the quest/content mods you selected e.g. the Snowytoes that is now available - select pause before mod.
During installation, the tool will pause at that point (Do not close it). 
Extract the Gui mod to IWDEE (note that it is a github package, so you need to move the dragonspear_UI++ folder and the setup....exe into the game folder
You manually can install the gui mod with its own setup.exe now
When finished, use "continue" in the tool to do the remaining installation.

**Comment by Timbo0o0o0** [comment]
It worked, thank you again for all your support for the game!
