### ISSUE TITLE
Missing TDD spell icons

### ISSUE THREAD

**Issue by MichtToen** [EE-Mod-Setup/EE-Mod-Setup#4]
I noticed that the TDD install did not copies all BAM files from TDD. 

The spells like Enbalm and Visions of Pain miss the spellbook icons.

**Comment by RoxanneSHS** [comment]
Is this an issue for the setup tool or rather something in TDDz mod itself?

**Comment by MichtToen** [comment]
I have no idea but i noticed it happens with BWS too,

**Comment by RoxanneSHS** [comment]
I opened an issue in TDDz github for it. I am not sure what the install tool can do here.
