### ISSUE TITLE
Faiths and Powers and Scales of Balance weapon overhauls

### ISSUE THREAD

**Issue by Hettikus** [EE-Mod-Setup/EE-Mod-Setup#42]
FnP component 0075 is at least partially incompatible with SoB 122. Druids get access to Longswords and Shortswords and maybe some other issues are there. Possibly combinations with SnB 121 or 124 lead to this error too but i never tried it.

**Comment by RoxanneSHS** [comment]
Both mods are made by the same author, so chances are that it will be fixed internally.

**Comment by RoxanneSHS** [comment]
meanwhile marked as conflict
