### ISSUE TITLE
Mod Link Duplicated

### ISSUE THREAD

**Issue by VeezyF** [EE-Mod-Setup/EE-Mod-Setup#43]
Small issue, but just wanted to bring it up.  I'm using the 2021 patch compilation with the IWD items removed.  In that list are the two following mods:

NindeEET
and
Alternatives: NindeEET

The first links to "https://github.com/RoxanneSHS/NindeEET/master.zip".  While it doesn't auto download, it's easy to manually get and state that it's a match.  However, the Alternatives mod links to "ttps://github.com/RoxanneSHS/NindeEET/master.zp".  The "h" in the link is missing and, obviously, if corrected links to the same spot as the main file.

I skipped past it, and everything is working properly, but I just wanted to make you aware of the issue.

**Comment by RoxanneSHS** [comment]
Thanks for reporting even though I cannot find the reason for the error.
The entry Alternatives: NindeEET makes no sense and is not configured anywhere in the tool (or the misspelled link). Something must have happened locally when writing your selection to the configuration files.
It seems to be a strange glitch that cannot be replicated.

**Comment by VeezyF** [comment]
No worries!  Thanks for looking into it!
