### ISSUE TITLE
Does this work with Linux?

### ISSUE THREAD

**Issue by ahungry** [EE-Mod-Setup/EE-Mod-Setup#44]
Hi all - does this work with linux (without using something like wine)? 

If not, are there any similar tools for a native linux setup/binary?   

I'm thinking if not, perhaps putting a little one together for the linux users.

**Comment by RoxanneSHS** [comment]
It only works on windows (or linux with something like wine, although I know too little about linux to provide details).
There are methods to install mods on linux but you have to do it manually.
