### ISSUE TITLE
Module issues

### ISSUE THREAD

**Issue by arosenow** [EE-Mod-Setup/EE-Mod-Setup#46]
Hi,

The classic dreams feature of BGEE Classic Movies appears to corrupt sleep so your characters are always fatigued and the sleep button needs 2 presses, I managed to play through until Baldur's gate until it corrupted and made the game unplayable. 
After uninstalling it, sleeping worked, however dialogue was corrupted so I needed a reinstall.

A version of npc_ee that was installed 5.1.3 seemed to break whilst executing the script and toggle advanced ai on and off repeatedly, but not finish the script. 5.7.1 from github seemed to fix it

**Comment by RoxanneSHS** [comment]
Thanks for the report.
- There is a possible fix for dream issues here https://github.com/RoxanneSHS/EET-Tweaks-and-Fixes but otherwise it may be the case that the mod has not been updated for game version 2.6.
- The NPC_EE is now updated.
