### ISSUE TITLE
Don't assign advanced ai by default component

### ISSUE THREAD

**Issue by arosenow** [EE-Mod-Setup/EE-Mod-Setup#47]
Hi,

In 2.6.6 this component appears to break the advanced ai completely, I can no longer select 'done' after choosing options

**Comment by RoxanneSHS** [comment]
Does this refer to 
4140=Don't Auto-Assign Advanced AI Scripting to Party
from Tweaks Anthology?
Is it possible some GUI mod interferes with it?

**Comment by arosenow** [comment]
That would be the component I'm using, I used the default settings for the
gui provided by the tool.
I've added quests, kits, tactics and convenience tweak components so far
from the menu to try.

I just did a reinstall because the faiths and powers spheres system
(default option) when combined with npc_ee (5.7.1) results in unselectable
spell slots.
This time I used the 4th (balanced) option and it seems to be working
correctly except the proficiencies issue I made a workaround for

**Comment by RoxanneSHS** [comment]
NPC_ee 5.7.1 is the current version, however the mod has been updated various times during the last few weeks (5.5 was just one month ago). So, there seems to be some issue under investigation and fixing. It may be just a momentary case of incompatibility that is hopefully resolved soon by the mod author (which is the same as faith and power, by the way).

**Comment by RoxanneSHS** [comment]
F&P updated meanwhile
