### ISSUE TITLE
Update Thalanthyr item upgrade to 4.2.5

### ISSUE THREAD

**Issue by chris-h-sg** [EE-Mod-Setup/EE-Mod-Setup#49]
Mod setup is currently using 4.2.4, version 4.2.5 is the latest and has been out for a few years, so presumably stable: https://github.com/CrevsDaak/thalan/archive/v4.2.5.zip

I was able to edit the ini files locally so the setup would download that version instead. Seems to work fine but I'm not sure what else I might need to include in order to make a PR.

**Comment by RoxanneSHS** [comment]
Done.
Hope it works...it cannot be worse than the older version anyway.

**Comment by chris-h-sg** [comment]
Thank you, that was quick!

Is there anything wrong with the mod? I haven't noticed anything major so far, just a few dialog oddities and the inconsistent power level of some items.

**Comment by RoxanneSHS** [comment]
Technically it should work like the earlier versions. Content is a  matter of taste, nothing I would use myself.
