### ISSUE TITLE
CtB not compatible with DSotSC spells

### ISSUE THREAD

**Issue by MichtToen** [EE-Mod-Setup/EE-Mod-Setup#5]
The spells and scrolls get messed up.

The effect is best seen with the spell Icebolt from DSotSC. The spell will vanish from the spellbook. Instead, many times, a 2nd Cats Grace will appear.

The worser effect is, that the scroll Icebolt, to learn the spell (can be found for example in the High Hedge shop), still shows the Icebolt data but will, when used, add the 2nd Cats Grace. That 2nd CG is marked in the Keeper as CG with the script Icebolt attached.

Some and more effects for other spells for DSotSC.

The safe way to install CtB with DSotSC is to disable the spells in the DSotSC install options, that will work.

**Comment by RoxanneSHS** [comment]
This is for EET, right? 
There are two options 
@1=DSotSC Wizard spells
@2=DSotSC Priest spells

Is one or both?

**Comment by MichtToen** [comment]
The wizard spells. I had not looked in the priest spel.

As long there is no fix i suggest to mark both options as conflict when ctb is enabled.

**Comment by RoxanneSHS** [comment]
Added the conflict.
