### ISSUE TITLE
Mod suggestion

### ISSUE THREAD

**Issue by Replay64** [EE-Mod-Setup/EE-Mod-Setup#52]
Hi, there are some mods that have been released recently or just came out, the boareskyr bridge scene, another fine hell and road to discovery i hope they can get into the EE setup tool these cover aspect of sod campaign, we lack some mods covering that part of the game. i hope you can check them out.

**Comment by RoxanneSHS** [comment]
Mods from Kerzenburg source cannot be supported.
The Return to Faerun mod and other mods add content to the SoD part of the game.

**Comment by Replay64** [comment]
i see thank you for the response.

Il giorno mer 21 dic 2022 alle ore 17:21 Roxanne ***@***.***>
ha scritto:
