### ISSUE TITLE
Customizable Save Directory

### ISSUE THREAD

**Issue by dark0dave** [EE-Mod-Setup/EE-Mod-Setup#56]
We should probably have a customizable save directory, current its hard coded to:

```
$MyBGEE=@MyDocumentsDir
```

This obviously does not work for linux & macos, but would also break if a windows user moved their save directory to some where else.

**Comment by dark0dave** [comment]
Happy to look into this :).

**Comment by RoxanneSHS** [comment]
This is talking about the place where the game puts its savegames, right?
In windows: The save directory is created by the original game(s) when you first launch them on your computer before even any mod is considered... The install tool has no influence on it, it just needs to access the location to get some configuration values, e.g. language to know which dialogue.tlk it needs for mods.
How any of that is configured on non-window is beyond my knowledge. I cannot provide information or support for it. If you figure it out and are able to provide some addition for linux, no problem - I have no knowledge whatsoever outside of windows.

**Comment by dark0dave** [comment]
Yep, I was thinking to add a customizable save directory like this:

![image](https://user-images.githubusercontent.com/52840419/209572629-d5ac0dc9-4890-45a0-a83a-f08c5fb697da.png)

**Comment by dark0dave** [comment]
We can have it default to the windows location, of 
```
$MyBGEE=@MyDocumentsDir
```

**Comment by dark0dave** [comment]
Agreed the tool has no effect on it. So we should be agnostic as possible, in-case the directory is no longer in the default location.

**Comment by dark0dave** [comment]
This functionality is similar to the way [eekeeper](https://eekeeper.sourceforge.io/) operates.

![image](https://user-images.githubusercontent.com/52840419/209573037-eda0d1b7-43c0-4fbe-96a7-bbac3d43b338.png)

**Comment by dark0dave** [comment]
If not we can trash the idea, and I can hack around it.

**Comment by RoxanneSHS** [comment]
Do not mix up two things here
- the $MyBGEE=@MyDocumentsDir is the one where the game itself saves to (line 61 etc in 09_install.au3
- the one in the screenshot is the default for the tool to use for the mod downloads and it is created on starting up the vbs file for windows as BWS_EE/EE Mod Downloads as a default. Windows users can use the select button right of it in the screen to change it. 
Maybe it is different in linux? In windows, the functionality is there.

**Comment by dark0dave** [comment]
Ahhh, so @MyDocumentsDir is the game directory? My bad :facepalm: .

**Comment by dark0dave** [comment]
I was attempting to change this:

```sh
	ElseIf StringInStr($g_Flags[14], 'EE') Then
		If $g_Flags[14]='BG1EE' Then
			$MyBGEE=@MyDocumentsDir&"\Baldur's Gate - Enhanced Edition"

		ElseIf $g_Flags[14]='BG2EE' Then
			$MyBGEE=@MyDocumentsDir&"\Baldur's Gate II - Enhanced Edition"
		ElseIf $g_Flags[14]='IWD1EE' Then
			$MyBGEE=@MyDocumentsDir&"\Icewind Dale - Enhanced Edition"
		ElseIf $g_Flags[14]='PSTEE' Then
			$MyBGEE=@MyDocumentsDir&"\Planescape Torment - Enhanced Edition"
		EndIf
		If Not FileExists($MyBGEE&'\save') Then DirCreate($MyBGEE&'\save')
```

**Comment by dark0dave** [comment]
```
If Not FileExists($MyBGEE&'\save') Then DirCreate($MyBGEE&'\save')
```

**Comment by dark0dave** [comment]
I encountered an error trying to find the save directory for PST.

**Comment by dark0dave** [comment]
- $MyBGEE=@MyDocumentsDir/save this is the default save game location
the mod download I am not changing, I am interested in changing the variable  $MyBGEE as this points to the location of the same games

**Comment by RoxanneSHS** [comment]
To clarify - this is how the EE games install on windows:
The game itself, including baldur.exe etc may be installed anywhere on your computer (for modding it is recommended that this should not be in games, steam, programs etc.) In that directory, referred to as game directory is a file called engine.lua (in pre-EE this used to be baldur.ini) that points to a central directory. You will have one for every game you may have installed (BGEE, BG2EE, PSTEE...EET creates another one). This is where screenshots, saves and a configuration file (baldur.lua) are located. The install tool reads and writes some information to that central directory as well.

**Comment by dark0dave** [comment]
Yes, thats the same on linux as well, there is a game directory which we call: $g_GameDir

and there is a save directory: $MyBGEE=@MyDocumentsDir/save

**Comment by dark0dave** [comment]
The @MyDocumentsDir points no where on linux. So in order for the tool to pick up the save directory we need to either provide a custom save location via an input (see eekeeper as an example) or create some custom linux flag which then points the default save location.

These are our two options for fixing this particular issue. I'd like to create a customizable save game directory option, for maximum flexibility. If we do not want to go down this route that is fine.

**Comment by dark0dave** [comment]
System 	Location
Windows 	[%USERPROFILE%](https://www.pcgamingwiki.com/wiki/Glossary:Game_data#User_profile)\Documents\Baldur's Gate - Enhanced Edition\save\
macOS (OS X) 	~/Documents/Baldur's Gate - Enhanced Edition/save/
Linux 	[$XDG_DATA_HOME](https://www.pcgamingwiki.com/wiki/Glossary:Game_data#Linux_paths)/Baldur's Gate - Enhanced Edition/save/

**Comment by RoxanneSHS** [comment]
The main problem with customization will be that it involves changes to the GUI. My previous experience with doing this in this very old software is not too good. I made very few changes only and all of them were cumbersome - GUI is not an area I am familiar with at all.

**Comment by dark0dave** [comment]
Thats fine, I can put in some flags instead if you prefer that approach :)

**Comment by dark0dave** [comment]
Thank you for your patience. Sorry it took so long to explain.

**Comment by AltFaden** [comment]
[dark0dave](https://github.com/dark0dave) 
Could you please explain how i can do that? Currently on Linux and dont know how to fix issue with save files. Cant install mods because of that. 
To [RoxanneSHS](https://github.com/RoxanneSHS)
This could be done also via .conf file, instead of UI. It should be easier and faster to do than editing UI.

**Comment by RoxanneSHS** [comment]
I am not a programmer and I have no clue about linux. I cannot code this myself but I am open to integrate whatever an expert in this area may want to contribute - all I can do is test that nothing would be broken in the current functionality.

**Comment by ToastedWookiee** [comment]
@AltFaden You can get around the save file issue by copying the folders needed, for BGEE, BG2EE, etc from in "~/.local/share/" to your wine drive. Generally should be in your home folder "~/.wine/drive_c", navigate like a Windows install drive and paste folders where they need to be under your Documents folder.
