### ISSUE TITLE
Adding 2 mods to the setup

### ISSUE THREAD

**Issue by Callimachus1** [EE-Mod-Setup/EE-Mod-Setup#57]
Hello!

Is it possible to add "Deities of Faerun" https://github.com/Raduziel/Deities-Of-Faerun
And/or "Bardic Wonders" https://github.com/ArtemiusI/Bardic-Wonders/
to the setup?

**Comment by RoxanneSHS** [comment]
Bardic Wonders is now added.
Deities is out of scope, that discussion is years old and no need to repeat all of it again.
