### ISSUE TITLE
Request to add Will to Power

### ISSUE THREAD

**Issue by Velgus** [EE-Mod-Setup/EE-Mod-Setup#61]
Kit mod adding four Psionic Classes. 

It works using a XXX/Cleric multiclasses activated using a skill from the XXX classes' kit, and has a component to rework usable weapons for such classes. If Faiths and Powers is installed, then it instead integrates with that mod's weapon usability system for clerics, so that optional component shouldn't be used.

https://github.com/UnearthedArcana/Will_to_Power

**Comment by RoxanneSHS** [comment]
On hold, too many open issues still, experimental status at best.
