### ISSUE TITLE
Faulty setting in Linux install

### ISSUE THREAD

**Issue by toynbeeidea166** [EE-Mod-Setup/EE-Mod-Setup#63]
Distro:  Manjaro
Game version:  GOG

I installed the three parts of BG, launched them all, created save games (BG1, SoD, BG2, ToB).  Then I ran wine App/Tools/AutoIt3.exe App/App.au3
 per the instructions.  The command line screen throws the following:

```
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
008c:fixme:imm:ImeSetActiveContext (0000000000010026, 0): stub
008c:fixme:imm:ImmReleaseContext (0000000000010020, 0000000000010026): stub
0024:fixme:wincodecs:jpeg_decoder_get_metadata_blocks stub
0024:fixme:imm:ImeSetActiveContext (0001005E, 1): stub
0024:fixme:imm:ImmReleaseContext (00010106, 0001005E): stub
0024:fixme:module:load_library unsupported flag(s) used 0x000032
0024:fixme:module:load_library unsupported flag(s) used 0x000032
0024:fixme:module:load_library unsupported flag(s) used 0x000032
0024:fixme:module:load_library unsupported flag(s) used 0x000032
!Faulty Game:EETsc_SetLang
!Faulty Game:EETsc_SetLangifyForGroupInstall
0120:fixme:file:server_get_file_info Unsupported info class e
bg2eetp not found
!No mod description: TravellersdFiles_BG2EEpe
!No mod description: mih_ip
!No mod description: dragonspear_ui++
```
The installer works as far as making mod selections, testing for conflicts, etc, but when it goes to actually install it says "Please start the game, choose the language you like, start and create a savegame." 

At no point, BTW, do I get to choose the language.  My game is in English, and that's where I want it.  But I guess based on "!Faulty Game:EETsc_SetLang" the installer isn't quite picking that up?

**Comment by RoxanneSHS** [comment]
Linux is not really supported by the tool even though some users seem to be able to make it work...
I cannot help much since I am no linux user but maybe the discussion here helps some? https://github.com/EE-Mod-Setup/EE-Mod-Setup/issues/56
