### ISSUE TITLE
2 questions

### ISSUE THREAD

**Issue by earthdude67** [EE-Mod-Setup/EE-Mod-Setup#70]
1. I would like to include a mod in my installation that is not currently included in the curated set.  The Dak'kon Zerth Blade upgrade mod available on beamdog.  How do I do that?  Pause the installation, run the setup_.exe?  Resume EET installation?
2. In prior versions of this tool, there was a mod that included a way to raise the cost of getting the Shadow Thieves' help to 150 or 200k.  I can't seem to locate that?

Thanks!

**Comment by RoxanneSHS** [comment]
1. Do that if you want it at a specific point in the sequence. You can insert an automatic pause by selecting the subsequent mod in the selection tree and use "pause before..." or you can hit pause during mod installation. (In the second case, the current component will finish installation until the pause will occur - with some mods this may take some time.)
2. Stratagems (SCS) has those options:
 @4170=Increase the price asked by Gaelan Bayle -> Gaelan wants 40,000 gold pieces
@4171=Increase the price asked by Gaelan Bayle -> Gaelan wants 60,000 gold pieces
@4172=Increase the price asked by Gaelan Bayle -> Gaelan wants 80,000 gold pieces
@4173=Increase the price asked by Gaelan Bayle -> Gaelan wants 100,000 gold pieces
@4174=Increase the price asked by Gaelan Bayle -> Gaelan wants 120,000 gold pieces
- if you use the Sandrah mod, the 120.000 rate will also be implemented automatically.

**Comment by earthdude67** [comment]
Apparently the Pause indicator isn't saved when you save your selections so
I ended up running the install without the pause since I didn't realize
that would happen.  I just ran that setup_ afterwards and I haven't
encountered anything bad....
