### ISSUE TITLE
Character creation blocker

### ISSUE THREAD

**Issue by andrei0mihai** [EE-Mod-Setup/EE-Mod-Setup#71]
Please help me find the mod that broke the character creation of Baldur's Gate campaign using EET, I cannot add the four points in the screen bellow. Another weird issue is that when I click on back button nothing happens, the same is with the Options menu > Gameplay page when I change some options and click Done, Cancel works fine.
This is my [compilation link](https://docs.google.com/document/d/1MFWJV8M_9vzOQWcsbyTwmZbuCzgAA0GCKDa3AqWcS30/edit?usp=sharing)
![image](https://user-images.githubusercontent.com/12158456/230676566-ef4ebe06-b673-4f9f-8361-a4873e7677de.png)

Thank you so much!
You are awesome!

**Comment by RoxanneSHS** [comment]
This probably is an issue with selecting some incompatible GUI mods. Look into the file weidu.log in your game directory to see which mods of that type you have installed. It may be easy to fix once the culprit is found.

**Comment by andrei0mihai** [comment]
I did another install with the same selection as EET_2023-Selection.ini from section Graphic, Portrait and sound mods. The character creation works now, but the button Done from Gameplay settings still is unresponsive and you cannot save any settings from there, it works for Feedback options screen and others inside Gameplay.
[weidu.log](https://docs.google.com/document/d/1IfMzyC7Q3wahwlSLQPL9UkanjokyAD0k_-z7JeB30bQ/edit?usp=sharing)

**Comment by RoxanneSHS** [comment]
You can try and just uninstall tipun gui mod. It is last in sequence, so it cannot break anything else. I have recently found some other problem with it in game, it sometimes cuts off the end of dialogue lines (I use it with EN language). Maybe some version of the mod has problems.
Note - you can still re-install it after character creation and play with it. GUI mods may be changed during ongoing games in most cases.

**Comment by andrei0mihai** [comment]
You are right, tipun gui mod was the issue, Thank you very much for your help [RoxanneSHS](https://github.com/RoxanneSHS)
