### ISSUE TITLE
Updating mods and translation problems

### ISSUE THREAD

**Issue by SergGrey** [EE-Mod-Setup/EE-Mod-Setup#72]
Hello, ran into a problem that when installing the mod "The BG1 NPC Project". After unpacking, the contents of the folder of the mod and the archive are identical, but during the installation, at least the file Russian translation(bg1npc\tra\russian\BG1NPC_TMP.TRA) changes and it has no line translation @783. Also, the translation in this file is different from the translation in the archive. Because of the lack of line translation, an error pops up:
```
ERROR: No translation provided for @783
ERROR: [bg1npc/Phase1/ITM/X#POLY.SPL] -> [override/X#POLY.SPL] Patching Failed (COPY) (Not_found)
ERROR: Not_found
The BG1 NPC Project: Banters, Quests, and Interjections (BG1 NPC Project) was not installed due to errors.
```
If you replace the translation file after the error and run the re-installation of this mod, the installation will go without errors. For the test used a minimal EET build (only unplugged mods) and "The BG1 NPC Project". When installing only the English language, no problems, but the content of the translation file is not checked.

Also encountered an error with the lack of Russian translations @163(AllThingsMazzy\translations\russian\setup-AllThingsMazzy.tra) for the mod "All Things Mazzy". In the file of English translations line is present. The text of the error, unfortunately, have not saved. This problem is fixed in the new version of this mod.

Also, found that in mods "Jini Romance" and "Minsc Friendship" there is a Russian language in mod files, but it is not displayed in the application. And mods "Sarevok Friendship", "Yoshimo Friendship" and "Chatty Imoen" already have Russian language in newer versions.

So put together today a list of mods that I would ask you to update the application, as afraid to manually swap their archives (for several days trying to build a compilation and constantly something will pop out, and trying to fix it, apparently, only makes it worse xD). 

List of mods:
[BG1RUS-EET](https://github.com/abalabokhin/BG1RUS-EET) - Newer version and improved version of "Full fixed russian translation for BG:EE".
[sod_rus](https://github.com/abalabokhin/sod_rus) - The new version of "SoD Translation RU" is out
[Baldur's Gate: Enhanced Edition Trilogy (EET)](https://github.com/abalabokhin/EET/tree/master) - New version of the "Enhanced Edition Trilogy
[change_russian_eet_terms](https://github.com/abalabokhin/change_russian_eet_terms) - mod to bring the terms of the Russian translation of BG2EE by Si1ver to the terms of EET. According to the instructions from [this site](https://arcanecoast.ru/forum/viewtopic.php?t=1544), the mod comes after "setup-EET_gui" but before "setup-EET_end".
[All-Things-Mazzy](https://github.com/Ratatoskr589/All-Things-Mazzy) - New version of the "All Things Mazzy" mod
[MinscFriendship](https://github.com/SpellholdStudios/MinscFriendship) - New version of the "Minsc Friendship" mod
[SarevokFriendship](https://github.com/SpellholdStudios/SarevokFriendship) - New version of the "Sarevok Friendship" mod
[YoshimoFriendship](https://github.com/SpellholdStudios/YoshimoFriendship) - New version of the "Yoshimo Friendship" mod
[ChattyImoen](https://github.com/AstroBryGuy/ChattyImoen) - New version of the "Chatty Imoen" mod
Rjali Romance seems to have a version 12.5, and the appendix has 12.0. But I think I read somewhere on the Internet that EET comes with a separately patched version of the mod. So I do not know if it will work, but just in case, I'll leave a [link](http://dragonshoard.blackwyrmlair.net/mods_download.php?mod=389).
Also, saw that "IWD in EET" and "IWD in EET Transition" are present in the application. As I understand it, there is already an updated version of this mod, but I could be wrong. [Found it here](https://arcanecoast.ru/forum/viewtopic.php?f=31&t=1247).
[IWD1_EET](https://github.com/11jo/IWD1_EET)
[IWD2_EET](https://github.com/11jo/IWD2_EET)
[Icewind_EET](https://github.com/11jo/Icewind_EET)

**Comment by RoxanneSHS** [comment]
I have made most of the proposed updates
Except
- change eet-terms >> this has no version or description, seems to be still work in progress
- EET >> the required patches to accept BGEE new imports are done by mod-fixpack but not using a branch of EET that misses many other official updates - your link is to some unknown branch, the fixpack updated the thp-files that checks BGEE installation
- IWD in EET >> I use the last tested and stable IWD1 version (no IWD2 yet), it works perfectly in the current version. It may be updated later, when communication can re-established and fixes be discussed. Suspended.

**Comment by SergGrey** [comment]
Thank you so much! Only, I didn't notice any changes in the git about "Jini Romance". I haven't tried it, but I assume that without changes in the config, even with the translation files, I will have the English version installed, not the Russian one xD. Also, wanted to know if I'm solving the "The BG1 NPC Project" problem correctly?

**Comment by RoxanneSHS** [comment]
My mistake, sorry, I missed the Jini issue. It is added now.

I am not sure what the issue is with BG1 NPC...the files are converted to UTF-8 during installation and maybe something there happens. However, that is mod internal processing and not related to install tool. So, it is something with format and RU special symbols that I cannot comment on. (Nobody else seems to have the issue, may it be something local?)

**Comment by SergGrey** [comment]
Thanks again. I doubt that the problem is with the encoding, as the text in the file is displayed normally, but the text of some lines is different from the text in the archive. It feels like something overwrites this file with an older translation during installation. But I do not understand, this is just a guess. If it helps you, I can send you both files during the next installation

**Comment by RoxanneSHS** [comment]
Check that you have the latest version of EE-Mod-Fixpack-master.zip. I remember there was an intermediate fix for missing RU files for BG1NPC but that is no longer needed because the mod itself was updated meanwhile. Maybe it was not updated in your mod download repository for any reason?

**Comment by SergGrey** [comment]
I'll check again, but I'm deleting everything, just in case, every time I try again. So there shouldn't be anything old left

**Comment by SergGrey** [comment]
Another question. The question is not quite on the topic of the program, so I apologize in advance. I want to try to play with mod "Imoen Romance", but the program says the incompatibility with the mods: "Ascension", "The Sandrah Saga", "Edwin Romance", "IEP Extended Banters" with the component "Imoen "Retrospection" dialogue for BGII: ToB", "The Longer Road EET".
Saw on the [forum](https://www.gibberlings3.net/forums/topic/28161-eet-v134-released/page/61/)(61-63 pages) that you were trying to resolve the incompatibility with "The Sandrah Saga" with the developer of "Imoen Romance". Did you end up solving this problem? And if not, I saw that you suggested changing/deleting some file so you could get through the game. Is there any way to play your mod with "Imoen Romance"?
I found in the version history of the "Ascension" git that the incompatibility with the mod was fixed in version ["2.0.11"](https://github.com/InfinityMods/Ascension/releases/tag/2.0.11). But whether there are other incompatibilities, I do not know.
With "Edwin Romance" mod, I could not find a description of the incompatibility problem anywhere. But the [readme](https://spellholdstudios.github.io/readmes/edwinromance-readme.html) describes the possibility of multi-romance with "Imoen Romance" through cheats.
At "IEP Extended Banters", I guess I just need to disable the component "Imoen "Retrospection" dialogue for BGII: ToB" as there is no other solution?
On the forum on "The Longer Road" [described](http://www.shsforums.net/topic/61610-tiny-issue-with-romance/) the problem of incompatibility and even suggested a solution (just do not take both characters in a group at a certain point). Developers took this into account, after that came out 2 updates, but the [history of changes](https://github.com/InfinityMods/LongerRoadEE/releases), I still do not understand whether this problem is fixed.

**Comment by RoxanneSHS** [comment]
I cannot answer the questions related to Imoen Romance because the original author abandoned the mod some years ago. Somebody fumbled around with it for some time, then somebody else started another branch that was full of bugs...at that point I just started to ignore the mod and its many incarnations. I am not aware of any version that was ever compatible with most other mods or even playable by itself.

**Comment by SergGrey** [comment]
Thanks for the clarification, then I will disable "Imoen Romance".
Started a new installation. The mod "Sarevok Romance" is missing a file on the link.
I would still like to try to install the new version of "IWD in EET". To combine it with the program, should I disable "IWD in EET" and "IWD in EET Transition" and enable "Pause before the mod" on "IWD in EET", then manually install all 3 mods and then continue installing through the program?
And if I want to install several mods with in different places(change_russian_eet_terms), can I include several pauses before different mods in the list of mods? In this case before "IWD in EET" and before "Enhanced Edition Trilogy End".

**Comment by SergGrey** [comment]
To my surprise, this time there were no problems with the translation of BG1NPC. But it's not the first time I got an error with your mod "Sandrah Saga I - Sandrah Appears":
```
Will uninstall   0 files for [SANDRAHNPC/SETUP-SANDRAHNPC.TP2] component 5.
Uninstalled      0 files for [SANDRAHNPC/SETUP-SANDRAHNPC.TP2] component 5.
ERROR: Not_found
Please make a backup of the file: SETUP-SANDRAHNPC.DEBUG and look for support at: Roxanne - https://github.com/RoxanneSHS
Automatically Skipping [SandrahNPC Creatures and Items] because of error.
Using Language [Russian (by arcanecoast.ru team)]
weidu_external/lang/english/ubsetup.tra file not found. Skipping...
weidu_external/lang/russian/ubsetup.tra file not found. Skipping...
[.\lang\ru_ru\dialog.tlk] created, 502031 string entries
[.\lang\ru_ru\dialogf.tlk] created, 502031 string entries

NOT INSTALLED DUE TO ERRORS SandrahNPC Creatures and Items

C:\Games\Baldur's Gate II - Enhanced Edition>

ERROR: cannot convert %CVMystra% or %%CVMystra%% to an integer
ERROR: [SandrahNPC\CRE/Sandrah.cre] -> [override\Sandrah.cre] Patching Failed (COPY) (Not_found)
ERROR: Not_found
SandrahNPC Creatures and Items (Sandrah Saga I - Sandrah Appears) was not installed due to errors.

You can try to repair the problem and start the installation of the component again. In this case please select "retry" after the repair.

If you don't want to spent time for that now, you can also continue without the component or exit the program. The Setup will continue with the installation of that component.
Enter [r]etry, [c]ontinue or [e]xit.
```
Last times I read somewhere on the forum that you referred to a problem with EET, I think. How do you deal with this error? Last time I just paused and manually installed this component, but I may have had issues with installing other mods that required this mod
[EE-Debug-Installation.log](https://github.com/EE-Mod-Setup/EE-Mod-Setup/files/11183855/EE-Debug-Installation.log)
[WeiDU.log](https://github.com/EE-Mod-Setup/EE-Mod-Setup/files/11183856/WeiDU.log)
[WeiDU-BGEE.log](https://github.com/EE-Mod-Setup/EE-Mod-Setup/files/11183857/WeiDU-BGEE.log)
[SETUP-SANDRAHNPC.DEBUG.log](https://github.com/EE-Mod-Setup/EE-Mod-Setup/files/11183860/SETUP-SANDRAHNPC.DEBUG.log)

**Comment by RoxanneSHS** [comment]
The easiest way to deal with this specific issue in an ongoing installation is to uninstall manually all components of SandrahNPC that are already installed. Then install the Sandrah mod again.

**Comment by SergGrey** [comment]
I must have bored you by now. If you have, let me know, I'll let you go xD. Once again, I made it to the end of the install. Was really hoping the game would run and I fixed all the bugs. But the game won't start again xD(just want to cry). The main problem, I do not start EET, as well as BG2EE (after starting the game, the process hangs, but the game window does not come out. The process takes about 15% of the CPU and about 75 RAM. Also, there is an error "Invalid token in menu: [comment] on line 6729, character 4", but I fixed it by changing "comment_0000" to "--achievements" in this file code "Baldur's Gate II - Enhanced Edition\override\UI.MENU"). Previously, and BG1EE after a complete installation does not start, but I removed, like, "BG1 NPCs for SoA & ToB" and BG1EE now runs. As I understand it, the problem in the file "Baldur's Gate II - Enhanced Edition\override\BGEE.LUA". If you remove it, the game runs. It was the same with BG1EE, but now everything is fine. Also, by tinkering, I determined that if you remove certain lines from the create in the buildQuestsTable function, the game will also run. I really hope you have some quick and easy way to determine the source of the problem or solution. For now I'm just going to try and re-install the build from the least amount of mods to the most (it's horrible).
And now some more bugs and my fixes.
To fix the error "Invalid token in menu: [comment] on line 6729, character 4" at game start, I replaced "comment_0000" with "--achievements" in "Baldur's Gate II - Enhanced Edition\override\UI.MENU":
```
button
{ comment_0000
	enabled "worldScreen == e:GetActiveEngine() and zZachShowAchivements == 1"
	area 13 660 46 48
	bam "ZZACHIVE"
	scaleToClip
	tooltip lua "zZachText.achievems"
	glow lua	"zZshowAch == 1"
	clickable lua "sidebarsGreyed ~= 1"
	action "
		Infinity_PushMenu('ACHIEVEMENTS')
	"
}
```
When installing "Rogue Rebalancing", a warning popped up, maybe because of it I had something broken, but it's not certain (taken as a note to test the installation without it):
```
Copying and patching 1 file ...
Patching RR#BUC03.ITM into store...
Copying and patching 1 file ...
Patching RR#BUC04.ITM into store...
Copying and patching 1 file ...
Patching RR#BUC04.ITM into store...

weidu_external/lang/english/ubsetup.tra file not found. Skipping...
weidu_external/lang/russian/ubsetup.tra file not found. Skipping...
[.\lang\ru_ru\dialog.tlk] created, 483638 string entries
[.\lang\ru_ru\dialogf.tlk] created, 483638 string entries

INSTALLED WITH WARNINGS     Additional equipment for Thieves and Bards

C:\Games\Baldur's Gate II - Enhanced Edition>

WARNING: no effects altered on MISC2P.ITM
Additional equipment for Thieves and Bards (Rogue Rebalancing) was installed with warnings.

You can analyse if the warning is severe now.
If the warning is harmless, please select continue. The Setup will then continue with the following component. Alternatively you can exit the setup now.
Enter [c]ontinue or [e].
```
Error when installing the component "Enhanced Scripts for Simulacrum" mod "Enhanced Powergaming Scripts":
```

ERROR: error loading [enhanced-powergaming-scripts/baf/upload/mocore.baf]
ERROR: Unix.Unix_error(20, "stat", "enhanced-powergaming-scripts/baf/upload/mocore.baf")
Install Enhanced Scripts for Simulacrum (Enhanced Powergaming Scripts) was not installed due to errors.
The following will not be installed without the component:

Sandrah Alternative Portraits or Class

Sandrah Saga II - Return to Faerun

Sandrah Saga III - Time of Troubles Revisited

Sandrah Saga I - Sandrah Appears:
0003: Mods Compatibility
0004: Sandrah Kit
0002: SandrahNPC for EET Core
0000: SandrahNPC Check for required Installation
0001: Sandrah Worldmap Entries


You can try to repair the problem and start the installation of the component again. In this case please select "retry" after the repair.

If you don't want to spent time for that now, you can also continue without the component or exit the program. The Setup will continue with the installation of that component.
Enter [r]etry, [c]ontinue or [e]xit.
```
And thank you for all your help and for babysitting me and my problems.
Just in case, I'm attaching files that may be useful.
[WeiDU.log](https://github.com/EE-Mod-Setup/EE-Mod-Setup/files/11184149/WeiDU.log)
[WeiDU-BGEE.log](https://github.com/EE-Mod-Setup/EE-Mod-Setup/files/11184156/WeiDU-BGEE.log)
[Setup-RR.debug.log](https://github.com/EE-Mod-Setup/EE-Mod-Setup/files/11184185/Setup-RR.debug.log)
[Setup-enhanced-powergaming-scripts.debug.log](https://github.com/EE-Mod-Setup/EE-Mod-Setup/files/11184186/Setup-enhanced-powergaming-scripts.debug.log)
[EE-Debug-Download.log](https://github.com/EE-Mod-Setup/EE-Mod-Setup/files/11184188/EE-Debug-Download.log)
[EE-Debug-Extraction.log](https://github.com/EE-Mod-Setup/EE-Mod-Setup/files/11184189/EE-Debug-Extraction.log)
[EE-Debug-Installation.log](https://github.com/EE-Mod-Setup/EE-Mod-Setup/files/11184190/EE-Debug-Installation.log)
[EE-Debug.log](https://github.com/EE-Mod-Setup/EE-Mod-Setup/files/11184191/EE-Debug.log)

**Comment by RoxanneSHS** [comment]
It sounds like a GUI mod causes the issues you describe (or maybe the combination of some GUI elements). I had a similar issue recently with the EN version of tipun's mod that was probably coded and tested for another language. The good thing with GUI mods is that you can work around them without having to do a complete re-installation of it all.
Look into weidu.log and maybe there are some components at the very end related to GUI that you can just uninstall.

**Comment by SergGrey** [comment]
In general, removing "Tipun's GUI" did not help. And for some reason it is installed almost at the beginning of the installation, sort of. Testing the mods section by section, so far I found out that my Sandra gives an error even with a clean EET build with the necessary Sandra mods. But your advice with manual reinstallation helps, thanks. The error with the "Enhanced Scripts for Simulacrum" component of the "Enhanced Powergaming Scripts" mod turns out to be caused by the mod itself and has been fixed in new versions long ago, sort of. Update, please, ["Enhanced Powergaming Scripts"](https://github.com/Gibberlings3/Enhanced-Powergaming-Scripts). Also found that there is a new version of ["Worldmap"](https://github.com/SpellholdStudios/BP-BGT-Worldmap). Continuing to test, maybe later I will ask for more updates mods)

**Comment by RoxanneSHS** [comment]
I updated powergaming...it may be better to remove it, though - to be decided later.
The worldmap update does nothing for EE or EET and is best skipped, the used one is stable and provides all the EE games need (including even IWDs in EET).

**Comment by SergGrey** [comment]
Why should it be removed? Is there a problem with it?

**Comment by Da1AnOnlyCrazy** [comment]
could you add Dragonspear UI++ mod?
https://forums.beamdog.com/discussion/50357/mod-dragonspear-ui-v2-42-now-compatible-with-bg2-ee

**Comment by RoxanneSHS** [comment]
The Dragonspear UI mod is there, look under Graphic Portrait and Sound Mods.

**Comment by Da1AnOnlyCrazy** [comment]
The following mod(s) could not be downloaded:

   Uldar the Barbarian: The Mod itself (UldarNPC.zip)
          https://www.dropbox.com/s/lu3ymv2j8l1w2dh/UldarNPC.zip?dl=1
   The White Queen: The Mod itself (The White Queen v6.93.zip)
          https://www.dropbox.com/sh/56dr4q8h2q7djri/AABqJdZlK5knm-B2m6ctgjW3a/COI%20-%20THE%20WHITE%20QUEEN/The%20White%20Queen%20v6.93.zip?dl=1
*  EE Mod Fixpack: The Mod itself (EE-Mod-Fixpack-master.zip)
          https://www.dropbox.com/s/apbyp6nod47pprw/EE-Mod-Fixpack-master.zip?dl=1
   Jan's Extended Quest: The Mod itself (JansQuest1.5.0.zip)
          https://www.dropbox.com/s/u35zhecotxb42qx/JansQuest1.5.0.zip?dl=1
   Eilistraee's Song: The Mod itself (Eilistraees Song v7.2.zip)
          https://www.dropbox.com/sh/56dr4q8h2q7djri/AAB1pULqPMaT3ZK_wY1aedgBa/EILISTRAEE%27S%20SONG/Eilistraees%20Song%20v7.2.zip?dl=1
   Sarevok Romance: The Mod itself (Sarevok Romance v1.4.zip)
          https://www.dropbox.com/s/pifofoz21t15zph/Sarevok%20Romance%20v1.4.zip?dl=1
   Fading Promises: The Mod itself (Fadingpromises-master.zip)
          https://www.dropbox.com/s/7a0e5pwcz9i370w/Fadingpromises-master.zip?dl=1
   Drake NPC: The Mod itself (Drake-16.zip)
          https://www.dropbox.com/s/3o4en8d2p0od1he/Drake-16.zip?dl=1
   Dark Horizons Tweaks: The Mod itself (DarkHorizonsTweaks.zip)
          https://www.dropbox.com/s/vetcdnio7y695yd/DarkHorizonsTweaks.zip?dl=1
   Garrick - Tales of a Troubadour: The Mod itself (garrick-tt_v1.26.7z)
          https://www.dropbox.com/s/bbbbx5bsgseodu5/garrick-tt_v1.26.7z?dl=1
*  WeiDU 64-bit: The Mod itself (WeiDU64.exe)
          https://www.dropbox.com/s/opixatf4352yl8g/weidu64.exe?dl=1
   I Shall Never Forget: The Mod itself (I Shall Never Forget v6.1.zip)
          https://www.dropbox.com/sh/56dr4q8h2q7djri/AABhfSVFA3_niKIpz3E1DdLYa/COI%20-%20I%20SHALL%20NEVER%20FORGET/I%20Shall%20Never%20Forget%20v6.1.zip?dl=1

*  Cannot proceed installation without this essential mod.

Some files could not be downloaded with the tool. Do you want the tool to try to load the mods again, provide the files yourself (see
remarks) or just continue?

it seems the files were downloaded, I forced the program to use zip file its says the files don't match the correct size

**Comment by RoxanneSHS** [comment]
Sounds like a very bad internet connection or some defender that is blocking dropbox.
Anyway, you can (f)orce the use of mods despite the size not matching, it is not relevant.
