### ISSUE TITLE
EEex and OlvynSpells

### ISSUE THREAD

**Issue by Viking8008** [EE-Mod-Setup/EE-Mod-Setup#73]
Hi! In your setup Tool there is neither 1 nor 2.

1) Can I install Eeex after EET_2023-Selection? I need only 3 bars near portraits to see rounds.

2) Why no OlvynSpells? And I guess I can't install it after ... or?

3) Can you add both of it?

**Comment by RoxanneSHS** [comment]
With those experiments you are on your own...just try it at the end, if something weird happens, you can uninstall it again. About Eeex - I will not even open that can of worms, there is no gain from it other than to corrupt valid installations.

**Comment by Viking8008** [comment]
Wow so much hate ;D
Is there any other mod that adds round bars or timers?

**Comment by RoxanneSHS** [comment]
There may be something in Hidden Gameplay Options Mod, even if I confess that I never used that mod myself.

**Comment by Viking8008** [comment]
Ok! Ty for answers!
