### ISSUE TITLE
Saving mod compilation pre download

### ISSUE THREAD

**Issue by arosenow** [EE-Mod-Setup/EE-Mod-Setup#74]
I've had some bad luck with needing to set admin before installing and lost my selected modlist. If we could save the chosen mods immediately after we've selected them all that would be helpful

**Comment by RoxanneSHS** [comment]
You can save your selection, even intermediate steps, any time you want. While in the mod selection tree, click on "options" at the top of the tree window and you have "save selection to file". You can save as many as you want if you give them individual names. With the same option you can load selections into the tree and either install or modify the loaded selection.
