### ISSUE TITLE
Error after selecting EET latest version

### ISSUE THREAD

**Issue by arosenow** [EE-Mod-Setup/EE-Mod-Setup#75]
![image](https://user-images.githubusercontent.com/20418497/233835020-073e1183-650a-408e-b852-642c14049318.png)
I updated to the latest version and seem to get the error shown after selecting an EET install

**Comment by RoxanneSHS** [comment]
I just checked and cannot reproduce the error. Furthermore, nothing has changed in that file for a long time. Maybe a problem with the local download or some local setting?

**Comment by arosenow** [comment]
It appears to have been the antivirus
