### ISSUE TITLE
Missed mods

### ISSUE THREAD

**Issue by simeonkosnitsky** [EE-Mod-Setup/EE-Mod-Setup#76]
this is saved versions from old installation 30.04.2021:
[nathaniel_v5.zip](https://github.com/EE-Mod-Setup/EE-Mod-Setup/files/11443649/nathaniel_v5.zip)
[Ulrien-SagaMaster.zip](https://github.com/EE-Mod-Setup/EE-Mod-Setup/files/11443652/Ulrien-SagaMaster.zip)

-------------

Ulrien Of Cormyr, Saga Master
https://www.dropbox.com/s/kmg5tvtcus95eh5/Ulrien-SagaMaster.zip?dl=1
sagaman[] = NA
Archive found (0,01 MB)
Archive is missing.

Nathaniel NPC
https://www.dropbox.com/s/cbs4de7mespuge4/Nathaniel_V5.zip?dl=1
Nathaniel[] = NA
Archive found (0,01 MB)
Archive is missing.

Verr'Sza BG2
https://www.dropbox.com/sh/56dr4q8h2q7djri/AACD1-TgFkrb_KSUBXtqBeI4a/VERR%27SZA%20BG2EE%20NPC/VerrBG2%20v1.2.zip?dl=0
VerrBG2[] = NA
Archive found (0,01 MB)
Archive is missing.
=>
https://downloads.weaselmods.net/download/verrsza-bg2ee/
Version
2.1

**Comment by RoxanneSHS** [comment]
The first link works for me, the other two have been updated.
