### ISSUE TITLE
BWFixpack breack BuTcHeRy 5.0.0 installation

### ISSUE THREAD

**Issue by simeonkosnitsky** [EE-Mod-Setup/EE-Mod-Setup#79]
Got multiple errors during 5.0.0 installation due to missed part of translation for lang\english

```
ERROR: No translation provided for @4
Continuing despite error.

SKIPPING: [Rebalanced Tazok and DigDag]
	UNDEFINED STRING:   @4
ERROR: No translation provided for @32
Continuing despite error.
```

[SETUP-BUTCHERY.DEBUG.log](https://github.com/GwendolyneFreddy/butchery/files/11445793/SETUP-BUTCHERY.DEBUG.log)

According investigation:
EE-Mod-Fixpack-master.zip replace butchery\_copy\lang\english\setup.tra

[BWFixpack]
Name=EE Mod Fixpack
Rev=GitHub Master
Type=R,S,T,E,F
Link=https://github.com/EE-Mod-Setup/EE-Mod-Setup
Down=https://www.dropbox.com/s/apbyp6nod47pprw/EE-Mod-Fixpack-master.zip?dl=1
Save=EE-Mod-Fixpack-master.zip
Size=11119142
Test=Big World Fixpack.bat:-
Tra=EN:0,--:0

**Comment by RoxanneSHS** [comment]
Fixed this here but it does not mean that the mod is now bug free. It is still best to avoid it.
