### ISSUE TITLE
EE-Mod-Setup-master\App\Config\Global\ some mod.ini bugged ?

### ISSUE THREAD

**Issue by davideOXC** [EE-Mod-Setup/EE-Mod-Setup#8]
_Today I tried it but I found some errors on download/check these mods by different size/name :_

Name=Enhanced Edition Trilogy
Rev=GitHub Latest Release
Type=F,R,S,T,E
Link=https://github.com/K4thos/EET
Down=https://github.com/K4thos/EET/archive/v1.0RC12.1.zip
Save=EET-1.0RC12.1.zip
Size=91363666 			-->**280460528** 

BG2EE_Name=Dark Side of the Sword Coast for BGT and EET
BG2EE_Rev=GitHub Master Branch
BG2EE_Type=S,T,E
BG2EE_Link=http://gibberlings3.net/forums/index.php?showtopic=27741
BG2EE_Down=http://lynxlynx.info/ie/modhub.php?K4thos/DSotSC&master
BG2EE_Save=DSotSC-master.zip
BG2EE_Size=27249698 --> **27249814**

Name=Sandrah Saga II - Return to Faerun
Rev=GitHub Master Branch
Type=R,S,T,E
Link=https://baldursextendedworld.com/Sandrah/
Down=http://lynxlynx.info/ie/modhub.php?RoxanneSHS/SandrahRtF&master
Save=SandrahRtF-master.zip
Size=271352149 --> **271353440**

Name=TDDz (EE-compatible installer for The Darkest Day)
Rev=GitHub Latest Release
Type=R,S,T,E
Link=https://github.com/BiGWorldProject/TDDz/blob/master/TDDz/README.md
Down=https://github.com/InfinityMods/TDDz/archive/TDDz_v1.2.7.zip
Save=TDDz-TDDz_v1.2.7.zip
Size=40309347    --> **47857292**

Name=Fishing for Trouble
Rev=3.2.4
Type=S,T,E
Link=http://www.spellholdstudios.net/ie/fft
Down=http://lynxlynx.info/ie/modhub.php?InfinityMods/FishingForTrouble&pre
Save=InfinityMods-FishingForTrouble-3.2.4-0-g363afdd.zip   -->   **InfinityMods-FishingForTrouble-3.2.4-0-gf4cd8db.zip**
Size=117127786   --> **177112442**

Name=Tales of Anegh
Rev=2.6
Type=S,T,E
Link=http://www.shsforums.net/topic/42996-tales-of-anegh/
Down=http://lynxlynx.info/ie/modhub.php?RoxanneSHS/ToA
Save=RoxanneSHS-ToA-V2.6-0-gf664f19.zip
Size=1591347  -->  **60023962**

Name=Tales of the Deep Gardens
Rev=12.4
Type=S,T,E
Link=http://www.spellholdstudios.net/ie/coi
Down=https://www.dropbox.com/sh/56dr4q8h2q7djri/AABqhcNd243RcKKr1cjtKJHta/COI%20-%20TALES%20OF%20THE%20DEEP%20GARDENS/Tales%20of%20the%20Deep%20Gardens%20v12.4.zip?dl=1
Save=Tales of the Deep Gardens v12.4.zip
Size=28946349   --> **29437470**

Name=Faiths and Powers
Rev=GitHub Latest Release
Type=R,S,T,E
Link=https://forums.beamdog.com/discussion/43174/faiths-and-powers-gods-of-the-realms-kitpack-and-divine-caster-spell-tweaks#latest
Down=http://lynxlynx.info/ie/modhub.php?UnearthedArcana/Faiths_and_Powers
Save=UnearthedArcana-Faiths_and_Powers-0.75.21.1-0-g44e4f99.zip
Size=675675  ---> **23655577**

...
Angelo NPC
Iylos
Saerileth NPC
`

Now I will try to contine with the ini fixed  

[EE-Debug-FileCheck.log](https://github.com/EE-Mod-Setup/EE-Mod-Setup/files/3537397/EE-Debug-FileCheck.log)

**Comment by davideOXC** [comment]
`Name=Iylos
Rev=3.0
Type=R,S,T,E
Link=http://www.shsforums.net/files/file/539-iylos/
Down=https://github.com/RoxanneSHS/IylosEET/archive/master.zip
Save=master.zip **-->  IylosEET-master.zip**
Size=5157470`

**Comment by davideOXC** [comment]
Name=Saerileth NPC
Rev=20
Type=S,T,E
Link=http://www.baldursgatemods.com/forums/index.php?board=16.0
Down=https://github.com/PaulaMigrate/Saerileth/archive/master.zip
Save=master.zip  **-->  Saerileth-master.zip**
Size=48795988

**Comment by davideOXC** [comment]
Name=Angelo NPC
Rev=Latest Github release
Type=R,S,T,E
Link=https://www.gibberlings3.net/files/file/686-angelo/
Down=https://github.com/Gibberlings3/Angelo/archive/master.zip
Save=master.zip  **--> Angelo-master.zip**
Size=13133112

**Comment by davideOXC** [comment]
Name=BGEE Leveled Spawns
Rev=0.3
Type=R,S,T,E
Link=http://forum.baldursgate.com/discussion/34840/bgee-leveled-spawns-mod-v0-3-updated-2014-12-27
Down=https://github.com/AstroBryGuy/BGEESpawn/archive/master.zip
Save=master.zip  **--> BGEESpawn-master.zip**
Size=2052248

**Comment by davideOXC** [comment]
I do not found the way to post on http://baldursextendedworld.com forum. I checked email and reconnected.

**Comment by RoxanneSHS** [comment]
Please see here https://github.com/EE-Mod-Setup/EE-Mod-Setup/issues/7

These are temporary issues in github rather than issues with the Install Tool. The files you quote are those updated after download, not the original configuration ini-files.

**Comment by davideOXC** [comment]
fifty fifty ... download repository as zip, produce an old image ... nut some problems are confimed.
I clonened repository with professional git client and some issues remains.
I close this cumulative issue and I will open single confirmed issue
