### ISSUE TITLE
EET_2023-Selection.ini setup completed getting invalid token upon starting bg2

### ISSUE THREAD

**Issue by Rothe123** [EE-Mod-Setup/EE-Mod-Setup#82]
![image](https://github.com/EE-Mod-Setup/EE-Mod-Setup/assets/114423787/ad0a0571-0047-4f4b-ae1c-06ac80c5c466)
getting couple of these errors when starting baldurs gate2 after installing the eet_2023-selection.ini
the install went great no issues during install were 2 manual imputs for a portrait and sounds for that character playing while in dialoge other than that it all installed fine. any help would be great since this compilation seems amazing! when i installed it was a clean install of both bg1ee and bg2ee and the documents folder i loaded each game created 1 character and made a save then started the install

**Comment by RoxanneSHS** [comment]
This may come from a GUI mod selection...
In the BG2EE/override folder (BG2EE being the directory you used for modding) you may look for a file UI.menu. If you open it with an editor you can look for the line with that error and check if there is something unusual there. (If you have Near Infinity, you can just open it there and look for the line). Without further information, I can only assume that some GUI function looks for an item that is not correctly defined.

**Comment by Rothe123** [comment]
Okay, Ill reinstall it from fresh and give you the file.

**Comment by Rothe123** [comment]
![image](https://github.com/EE-Mod-Setup/EE-Mod-Setup/assets/114423787/5b5ddef7-7d81-422b-b795-e7781a5dcdd0)

![image](https://github.com/EE-Mod-Setup/EE-Mod-Setup/assets/114423787/f126e089-6eb7-4fc2-86ad-048dca6ec6d8)

![image](https://github.com/EE-Mod-Setup/EE-Mod-Setup/assets/114423787/11a8fdf5-0a34-4df2-9a98-8a0fd5235706)

here are the initial 3 errors after starting the game
i tried both the ui.menu and ui.rar did they upload?

**Comment by Rothe123** [comment]
says we dont support that file type.

**Comment by Rothe123** [comment]
![image](https://github.com/EE-Mod-Setup/EE-Mod-Setup/assets/114423787/37521344-f368-4dbc-a11b-334bcff242f1)
2988 FROM ui.menu using near infinity
![image](https://github.com/EE-Mod-Setup/EE-Mod-Setup/assets/114423787/472c1887-14a7-4075-9e64-07cd8a5ea0d3)
2997 ""
![image](https://github.com/EE-Mod-Setup/EE-Mod-Setup/assets/114423787/28382855-84f3-4fdb-a480-8a42bb859442)
6751

**Comment by Rothe123** [comment]
maybe you can see what is wrong..

**Comment by Rothe123** [comment]
went i playedi t for a little while got to xar and other guy npc's and their character records were all messed up couldnt even access them.

**Comment by Rothe123** [comment]
[UI.zip](https://github.com/EE-Mod-Setup/EE-Mod-Setup/files/11639981/UI.zip)
ah zip doh sorry im stupid.

**Comment by RoxanneSHS** [comment]
You may try this file to put into the respective override folder.
https://www.dropbox.com/s/txto03mf0bb3obv/UIrepair.zip?dl=1

**Comment by Rothe123** [comment]
the errors are gone I will create a character and see how it goes from here thank you!
