### ISSUE TITLE
Add  IWD_EET_Integration for better IWD in EET support.

### ISSUE THREAD

**Issue by SomeGuyDoinWork** [EE-Mod-Setup/EE-Mod-Setup#84]
https://github.com/subtledoctor/IWD_EET_Integration

For Tipun's IWD in EET.

Needs all 3 of his mods + eet patch if using with that.

**Comment by RoxanneSHS** [comment]
Currently only IWD1 in EET is mature and tested and the install tool offers full integration if you follow the advice in the pdf manual of the tool. This is well tested by now and stable.
