### ISSUE TITLE
Wilson Chronicles v1.92 no longer downloadable.

### ISSUE THREAD

**Issue by SomeGuyDoinWork** [EE-Mod-Setup/EE-Mod-Setup#85]
Looks like needs to be updated to v2.1 from https://downloads.weaselmods.net/download/wilson-chronicles/

The download link that's 404 is:
https://www.dropbox.com/sh/56dr4q8h2q7djri/AADEyl-tYV8zhjK8eoGvpneBa/WILSON%20CHRONICLES/WilsonChronicles%20v1.92.zip?dl=1

**Comment by RoxanneSHS** [comment]
It is now updated, also supporting Spanish language now.
