### ISSUE TITLE
A7-GolemConstruction.ini has different size from downloaded today

### ISSUE THREAD

**Issue by davideOXC** [EE-Mod-Setup/EE-Mod-Setup#9]
git version is: 
![image](https://user-images.githubusercontent.com/7692937/63643521-7f23df80-c6d2-11e9-9df8-e533dfc95738.png)

https://github.com/EE-Mod-Setup/EE-Mod-Setup/blob/master/App/Config/Global/A7-GolemConstruction.ini

My fixed version is:
![image](https://user-images.githubusercontent.com/7692937/63643479-4df6df80-c6d1-11e9-8e89-c6bbcde48c96.png)

because when manual download it, the size is different:

![image](https://user-images.githubusercontent.com/7692937/63643496-d07f9f00-c6d1-11e9-98dc-a11ca3f08f2e.png)

**Comment by RoxanneSHS** [comment]
This should not cause any problems. If you are asked by the tool you can simply (f)orce the use. It is a notification rather than an error.
