### ISSUE TITLE
Can't interact with Rilsa's body

### ISSUE THREAD

**Issue by enderandrew** [EE-Mod-Setup/EE-Mod-Setup#91]
I'm doing the Neera side-quest. I follow a goblin to a cave and find a dead body. Later I meet Magreb who wants me to find the body of Rilsa. I see the body no problem. I can loot the gear on top. I can click precisely where the icon turns into that set of two circular arrows, but nothing. I reload and try talking to Magreb first. Same thing. I get the same behavior. I can find the body. I get the weird icon to interact with the body, but clicking does nothing.
[EE-Debug.zip](https://github.com/EE-Mod-Setup/EE-Mod-Setup/files/12270619/EE-Debug.zip)

**Comment by enderandrew** [comment]
The issue come from A7-TotLM-BG2EE who replace NETRIG1.BCS and deactivate the trigger for Rizzla body...

I have noticed the same issue from IWD1_EET, it seem that a common file from Heart of Winter is overlaping.

**Comment by RoxanneSHS** [comment]
A7-TotLM-BG2EE in fact overwrites NETRIG1.bcs (Since it is a HOW file, IWD may do the same).

You can either C:CreateCreature("Neinvi") but it may be hard to trigger the dialogue. Otherwise C:SetGlobal("BURY_RILSA","GLOBAL",2) to set the option for her husband's dialogue and finish the quest.

**Comment by RoxanneSHS** [comment]
I have reported this to the mod author. It will only appear in EET, so it is more an EET compatibility issue than a bug for the BG2 mod...

**Comment by enderandrew** [comment]
Thanks!

**Comment by enderandrew** [comment]
C:SetGlobal("BURY_RILSA","GLOBAL",2) makes the body disappear but the husband still won't finish the quest. I may need the ring in my inventory as well.

**Comment by RoxanneSHS** [comment]
C:CreateItem("NERING01")

**Comment by enderandrew** [comment]
That worked. Thanks!
