### ISSUE TITLE
Problem with EE Instalation Sandrah Appear

### ISSUE THREAD

**Issue by vpuebla** [EE-Mod-Setup/EE-Mod-Setup#92]
Hello:

I am doing a big installation with the majority of big mods. Near to the end when the EE Mod Set up is installing Sandrah Saga I, appear an installation issue

**ERROR: COPY_TRANS B!GAVINJ state #2180 out of range 0-1207, SKIPPED
ERROR: Cannot process COPY_TRANS (Failure("COPY_TRANS out of range"))
ERROR: processing COPY_TRANS [SandrahNPC/Mods/bgavinsan.d]: Failure("COPY_TRANS out of range")
ERROR: Failure("COPY_TRANS out of range")
Mod Interactions (Sandrah Saga I - Sandrah Appears) was not installed due to errors.

You can try to repair the problem and start the installation of the component again. In this case please select "retry" after the repair_.**

One time I finished the installation with this problem, but the Sandra Sagah mod lost a lot of content. I play a little and for example Hiass is not recruitable. And I imagine that we will have a lot of problems during the playthrough

It would be possible to fix this problem? I am using the last version discharged by the EE Mod Set up SandraEET 2.07

Best regards

Victor

**Comment by RoxanneSHS** [comment]
Download this https://www.dropbox.com/scl/fi/e6gf129lhwyuzkcbkyes4/bgavinsan.zip?rlkey=8kxdsp6pvk3pke62wzh552mv8&dl=1
Extract the file to your BG2EE SandrahNPC/Mods/bgavinsan.d to overwrite the existing file.

**Comment by RoxanneSHS** [comment]
Now fixed in updated mod version.

**Comment by vpuebla** [comment]
Many thanks Roxanne. Now all is OK. I am playing my new playthrough with
IWD in EET

Do you see viable in some moment include IWD 2 in EET and the mod shades of
sword coast in a big compilación?

Many thanks for your excellent work

Best regards

Victor

**Comment by RoxanneSHS** [comment]
No to both mods, IWD2 is not yet stable enough, the other has too many incompatibilities in a larger context.
