### ISSUE TITLE
Please start the game, choose the language you like, start and create a savegame

### ISSUE THREAD

**Issue by Varlinn** [EE-Mod-Setup/EE-Mod-Setup#93]
This message appears every time and the installer closes, despite the fact that I have both games installed, unmodded, and have existing save files for both games. I've tried reinstalling the games with no change.

**Comment by RoxanneSHS** [comment]
If you have the latest game versions (2.6) then check issue #27 to see if that helps. Errors like that are due to local settings on your computer not due to bugs in the tool.
