### ISSUE TITLE
Error installing EET end 

### ISSUE THREAD

**Issue by CaveofLemons** [EE-Mod-Setup/EE-Mod-Setup#95]
I'm pretty new to modding with BG, but near the end of the installation process I've been getting this error notice

ERROR Installing [EET end (last mod in install order) -> Standard installation], rolling back to previous state
Will uninstall   2 files for [EET_END/EET_END.TP2] component 0.
Uninstalled      2 files for [EET_END/EET_END.TP2] component 0.
ERROR: Failure("ERROR: READ_2DA_ENTRY_FORMER failed on variable %pdialog_37_2%")
PLEASE email the file SETUP-EET_END.DEBUG to K4thos (swit)
Automatically Skipping [EET end (last mod in install order) -> Standard installation] because of error.
Using Language [English]
weidu_external/lang/english/ubsetup.tra file not found. Skipping...

NOT INSTALLED DUE TO ERRORS EET end (last mod in install order) -> Standard installation

D:\Games\Baldur's Gate II - Enhanced Edition>

ERROR: [BGDIALOG.2da] -> [override/BGDIALOG.2da] Patching Failed (COPY) (Failure("ERROR: READ_2DA_ENTRY_FORMER failed on variable %pdialog_37_2%"))
ERROR: [CAMPAIGN.2DA] -> [.../CAMPAIGN.2DA] Patching Failed (COPY) (Failure("ERROR: READ_2DA_ENTRY_FORMER failed on variable %pdialog_37_2%"))
ERROR: Failure("ERROR: READ_2DA_ENTRY_FORMER failed on variable %pdialog_37_2%")
Enhanced Edition Trilogy End (standard) (Enhanced Edition Trilogy End) was not installed due to errors.

Without this component the installation cannot be continued.

You can try to repair the problem and install the component again afterwards. In this case please select "retry" after the repair.

If you don't want to spend time on that now, you can also exit the program.
Enter [r]etry or [e]xit.

For reference, the D drive is a secondary ssd so it shouldn't be related to windows protection. I've tried again with a fresh install of the game but it must be due to one of the mods selected, any tips? 

I added the two relevant text files to this gist below:
https://gist.github.com/CaveofLemons/13b7d826b2fd7b3b6fe72ff6cbd5b1ca

**Comment by RoxanneSHS** [comment]
From the data provided it seems that some other mod introduced an error before (or there was a write error due to local protection on your computer). Take a look at the 2da files (probably in your game's override folder) pdialog.2da and campaign.2da and see if you find something abnormal.

**Comment by CaveofLemons** [comment]
Not totally sure what to look for specifically, but I'll provide the copied text from the 2da files here

https://gist.github.com/CaveofLemons/9ebd9c398f826c986dadee809d3fbe51#file-campaign-2da

**Comment by CaveofLemons** [comment]
> From the data provided it seems that some other mod introduced an error before (or there was a write error due to local protection on your computer). Take a look at the 2da files (probably in your game's override folder) pdialog.2da and campaign.2da and see if you find something abnormal.

Not totally sure what to look for specifically, but I'll provide the copied text from the 2da files here

https://gist.github.com/CaveofLemons/9ebd9c398f826c986dadee809d3fbe51#file-campaign-2da

**Comment by RoxanneSHS** [comment]
Sorry, I do not see anything wrong with those files either.
Another option to look at is BGDialog.2da

**Comment by CaveofLemons** [comment]
> Sorry, I do not see anything wrong with those files either. Another option to look at is BGDialog.2da

Here's BGDialog.2da 
https://gist.github.com/CaveofLemons/611d9cc55a3e6c5220eabb6d8360a200

I have a feeling it's one of the mods I selected, since before everything installed fine but I wanted to reinstall after I accidentally installed two different components that messed with the portraits picker, and one of the new mods I selected must be the culprit. Unfortunately I didn't save a compilation of the older mod list so I have nothing to compare it to.

**Comment by RoxanneSHS** [comment]
The last line in BGDialog.2da looks strange, my assumption is that it should not even be there, it refers to Aerie from the Wings mod but has no reference to a joined-dialog file. The mod itself does not add new files but just adds to existing Aerie files, so I do not know why EET_end tries to add a line here.
I have never seen this error before.

**Comment by CaveofLemons** [comment]
> The last line in BGDialog.2da looks strange, my assumption is that it should not even be there, it refers to Aerie from the Wings mod but has no reference to a joined-dialog file. The mod itself does not add new files but just adds to existing Aerie files, so I do not know why EET_end tries to add a line here. I have never seen this error before.

Thanks to your pointer, it actually was the Aerie from the Wings mod! I had the Aerie in BGEE mod checked, so maybe they had a conflict of some sort? Granted I did also go through the EET compatible mods list and disabled some other mods from my old load order which may or may not have helped, but we finally got everything in working order again.
