### ISSUE TITLE
ZIP archive not working

### ISSUE THREAD

**Issue by Mateusz-Jan** [EE-Mod-Setup/EE-Mod-Setup#96]
Hi,

ZIP archive is not working, I tried with 3 different programs-7zip, winzip and bandizip.

Please attach working ZIP . 

Regards,

Mat

**Comment by RoxanneSHS** [comment]
If you downloaded from here https://github.com/EE-Mod-Setup/EE-Mod-Setup/archive/master.zip it should open with e.g. 7-zip. Just tested again on windows 11 64bit but works with other windows versions as well. Check if your local program is the correct one for your system. Also check if the download was complete. It must be a local issue on your side.
