### ISSUE TITLE
Has anyone had issues with 'Travellers' and Galileus dialogue loop?

### ISSUE THREAD

**Issue by brildhog** [EE-Mod-Setup/EE-Mod-Setup#98]
I have a ton of mods and used PI to set up. So I am aware that this may be peculiar to me.
Thought I would check. 

When I speak to Galileus. If I pick options 2 or 3 the dialogue loops without end. It follows PC having just one dialogue option to pick - "what meaning has the appearance of a new star...". From what I can see apart from NPC mod dialogue interjections, the only mod affecting Galilius (apart from EET end & SCS) is Travellers.

Anyhow I can easily progress by picking dialogue option 1. (Or ignoring him). But thought I would flag up, in case it may affect more than me...

**Comment by RoxanneSHS** [comment]
This is solved in v0.84 of the Travellers mod - check in your weidu.log if you maybe have an older version.

**Comment by brildhog** [comment]
Thanks for the reply...
My log says: 
~TRAVELLERS\TRAVELLERS.TP2~ #0 #0 // Travellers in Faerun: v0.84
~TRAVELLERS\TRAVELLERS.TP2~ #0 #1 // Arkanis Gath's Investigation: v0.84
~TRAVELLERS\TRAVELLERS.TP2~ #0 #2 // The Peddler: v0.84

**Comment by brildhog** [comment]
Ok, thanks
After this playthrough, I will try and put Travellers later in the load order - after the NPC mods - a few of which ad interjections. I think this is what the Set-up tool does, if I am reading the documentation correctly...
Nice idea for a mod though...
