### ISSUE TITLE
[Documentation] Could the README explain what this helper tool brings to the table?

### ISSUE THREAD

**Issue by rubyFeedback** [EE-Mod-Setup/EE-Mod-Setup#99]
I am a bi confused as to which tool to use and which not.

Already some time ago I realised that weidu itself is awkward and causes issues
when I have many mods installed (for instance, weidu uninstalls mods, then
re-installs mods, which takes about 1 hour or so and I still had issues afterwards).

Could the main README document when and why this tool is used compared to
OTHER tools? How this interplays and why it should be installed? Right now after
reading the README this is still unclear to me.

**Comment by RoxanneSHS** [comment]
It is detailed here https://github.com/EE-Mod-Setup/EE-Mod-Setup/blob/master/Documents/The%20EE%20Game%20Setup%20Tool.pdf
You do not install the tool but you use it to install mods.
